// Code generated by ent, DO NOT EDIT.

package carpoolresetaccountstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the carpoolresetaccountstate type in the database.
	Label = "carpool_reset_account_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpstreamIdentityHash holds the string denoting the upstream_identity_hash field in the database.
	FieldUpstreamIdentityHash = "upstream_identity_hash"
	// FieldRepresentativeAccountID holds the string denoting the representative_account_id field in the database.
	FieldRepresentativeAccountID = "representative_account_id"
	// FieldBaselineComplete holds the string denoting the baseline_complete field in the database.
	FieldBaselineComplete = "baseline_complete"
	// FieldLastObservedAt holds the string denoting the last_observed_at field in the database.
	FieldLastObservedAt = "last_observed_at"
	// FieldLastCompleteAt holds the string denoting the last_complete_at field in the database.
	FieldLastCompleteAt = "last_complete_at"
	// FieldHealthStatus holds the string denoting the health_status field in the database.
	FieldHealthStatus = "health_status"
	// FieldKnownCreditCount holds the string denoting the known_credit_count field in the database.
	FieldKnownCreditCount = "known_credit_count"
	// FieldIncompleteReason holds the string denoting the incomplete_reason field in the database.
	FieldIncompleteReason = "incomplete_reason"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the carpoolresetaccountstate in the database.
	Table = "carpool_reset_account_states"
)

// Columns holds all SQL columns for carpoolresetaccountstate fields.
var Columns = []string{
	FieldID,
	FieldUpstreamIdentityHash,
	FieldRepresentativeAccountID,
	FieldBaselineComplete,
	FieldLastObservedAt,
	FieldLastCompleteAt,
	FieldHealthStatus,
	FieldKnownCreditCount,
	FieldIncompleteReason,
	FieldRevision,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpstreamIdentityHashValidator is a validator for the "upstream_identity_hash" field. It is called by the builders before save.
	UpstreamIdentityHashValidator func(string) error
	// DefaultBaselineComplete holds the default value on creation for the "baseline_complete" field.
	DefaultBaselineComplete bool
	// DefaultHealthStatus holds the default value on creation for the "health_status" field.
	DefaultHealthStatus string
	// HealthStatusValidator is a validator for the "health_status" field. It is called by the builders before save.
	HealthStatusValidator func(string) error
	// DefaultKnownCreditCount holds the default value on creation for the "known_credit_count" field.
	DefaultKnownCreditCount int
	// IncompleteReasonValidator is a validator for the "incomplete_reason" field. It is called by the builders before save.
	IncompleteReasonValidator func(string) error
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CarpoolResetAccountState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpstreamIdentityHash orders the results by the upstream_identity_hash field.
func ByUpstreamIdentityHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamIdentityHash, opts...).ToFunc()
}

// ByRepresentativeAccountID orders the results by the representative_account_id field.
func ByRepresentativeAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepresentativeAccountID, opts...).ToFunc()
}

// ByBaselineComplete orders the results by the baseline_complete field.
func ByBaselineComplete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaselineComplete, opts...).ToFunc()
}

// ByLastObservedAt orders the results by the last_observed_at field.
func ByLastObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastObservedAt, opts...).ToFunc()
}

// ByLastCompleteAt orders the results by the last_complete_at field.
func ByLastCompleteAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCompleteAt, opts...).ToFunc()
}

// ByHealthStatus orders the results by the health_status field.
func ByHealthStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealthStatus, opts...).ToFunc()
}

// ByKnownCreditCount orders the results by the known_credit_count field.
func ByKnownCreditCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKnownCreditCount, opts...).ToFunc()
}

// ByIncompleteReason orders the results by the incomplete_reason field.
func ByIncompleteReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncompleteReason, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
