// Code generated by ent, DO NOT EDIT.

package carpoolresetaccountstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldID, id))
}

// UpstreamIdentityHash applies equality check predicate on the "upstream_identity_hash" field. It's identical to UpstreamIdentityHashEQ.
func UpstreamIdentityHash(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldUpstreamIdentityHash, v))
}

// RepresentativeAccountID applies equality check predicate on the "representative_account_id" field. It's identical to RepresentativeAccountIDEQ.
func RepresentativeAccountID(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldRepresentativeAccountID, v))
}

// BaselineComplete applies equality check predicate on the "baseline_complete" field. It's identical to BaselineCompleteEQ.
func BaselineComplete(v bool) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldBaselineComplete, v))
}

// LastObservedAt applies equality check predicate on the "last_observed_at" field. It's identical to LastObservedAtEQ.
func LastObservedAt(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldLastObservedAt, v))
}

// LastCompleteAt applies equality check predicate on the "last_complete_at" field. It's identical to LastCompleteAtEQ.
func LastCompleteAt(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldLastCompleteAt, v))
}

// HealthStatus applies equality check predicate on the "health_status" field. It's identical to HealthStatusEQ.
func HealthStatus(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldHealthStatus, v))
}

// KnownCreditCount applies equality check predicate on the "known_credit_count" field. It's identical to KnownCreditCountEQ.
func KnownCreditCount(v int) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldKnownCreditCount, v))
}

// IncompleteReason applies equality check predicate on the "incomplete_reason" field. It's identical to IncompleteReasonEQ.
func IncompleteReason(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldIncompleteReason, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldRevision, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpstreamIdentityHashEQ applies the EQ predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashEQ(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashNEQ applies the NEQ predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashNEQ(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashIn applies the In predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashIn(vs ...string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldUpstreamIdentityHash, vs...))
}

// UpstreamIdentityHashNotIn applies the NotIn predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashNotIn(vs ...string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldUpstreamIdentityHash, vs...))
}

// UpstreamIdentityHashGT applies the GT predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashGT(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashGTE applies the GTE predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashGTE(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashLT applies the LT predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashLT(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashLTE applies the LTE predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashLTE(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashContains applies the Contains predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashContains(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldContains(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashHasPrefix applies the HasPrefix predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashHasPrefix(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldHasPrefix(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashHasSuffix applies the HasSuffix predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashHasSuffix(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldHasSuffix(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashEqualFold applies the EqualFold predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashEqualFold(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEqualFold(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashContainsFold applies the ContainsFold predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashContainsFold(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldContainsFold(FieldUpstreamIdentityHash, v))
}

// RepresentativeAccountIDEQ applies the EQ predicate on the "representative_account_id" field.
func RepresentativeAccountIDEQ(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldRepresentativeAccountID, v))
}

// RepresentativeAccountIDNEQ applies the NEQ predicate on the "representative_account_id" field.
func RepresentativeAccountIDNEQ(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldRepresentativeAccountID, v))
}

// RepresentativeAccountIDIn applies the In predicate on the "representative_account_id" field.
func RepresentativeAccountIDIn(vs ...int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldRepresentativeAccountID, vs...))
}

// RepresentativeAccountIDNotIn applies the NotIn predicate on the "representative_account_id" field.
func RepresentativeAccountIDNotIn(vs ...int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldRepresentativeAccountID, vs...))
}

// RepresentativeAccountIDGT applies the GT predicate on the "representative_account_id" field.
func RepresentativeAccountIDGT(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldRepresentativeAccountID, v))
}

// RepresentativeAccountIDGTE applies the GTE predicate on the "representative_account_id" field.
func RepresentativeAccountIDGTE(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldRepresentativeAccountID, v))
}

// RepresentativeAccountIDLT applies the LT predicate on the "representative_account_id" field.
func RepresentativeAccountIDLT(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldRepresentativeAccountID, v))
}

// RepresentativeAccountIDLTE applies the LTE predicate on the "representative_account_id" field.
func RepresentativeAccountIDLTE(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldRepresentativeAccountID, v))
}

// RepresentativeAccountIDIsNil applies the IsNil predicate on the "representative_account_id" field.
func RepresentativeAccountIDIsNil() predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIsNull(FieldRepresentativeAccountID))
}

// RepresentativeAccountIDNotNil applies the NotNil predicate on the "representative_account_id" field.
func RepresentativeAccountIDNotNil() predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotNull(FieldRepresentativeAccountID))
}

// BaselineCompleteEQ applies the EQ predicate on the "baseline_complete" field.
func BaselineCompleteEQ(v bool) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldBaselineComplete, v))
}

// BaselineCompleteNEQ applies the NEQ predicate on the "baseline_complete" field.
func BaselineCompleteNEQ(v bool) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldBaselineComplete, v))
}

// LastObservedAtEQ applies the EQ predicate on the "last_observed_at" field.
func LastObservedAtEQ(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldLastObservedAt, v))
}

// LastObservedAtNEQ applies the NEQ predicate on the "last_observed_at" field.
func LastObservedAtNEQ(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldLastObservedAt, v))
}

// LastObservedAtIn applies the In predicate on the "last_observed_at" field.
func LastObservedAtIn(vs ...time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldLastObservedAt, vs...))
}

// LastObservedAtNotIn applies the NotIn predicate on the "last_observed_at" field.
func LastObservedAtNotIn(vs ...time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldLastObservedAt, vs...))
}

// LastObservedAtGT applies the GT predicate on the "last_observed_at" field.
func LastObservedAtGT(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldLastObservedAt, v))
}

// LastObservedAtGTE applies the GTE predicate on the "last_observed_at" field.
func LastObservedAtGTE(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldLastObservedAt, v))
}

// LastObservedAtLT applies the LT predicate on the "last_observed_at" field.
func LastObservedAtLT(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldLastObservedAt, v))
}

// LastObservedAtLTE applies the LTE predicate on the "last_observed_at" field.
func LastObservedAtLTE(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldLastObservedAt, v))
}

// LastObservedAtIsNil applies the IsNil predicate on the "last_observed_at" field.
func LastObservedAtIsNil() predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIsNull(FieldLastObservedAt))
}

// LastObservedAtNotNil applies the NotNil predicate on the "last_observed_at" field.
func LastObservedAtNotNil() predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotNull(FieldLastObservedAt))
}

// LastCompleteAtEQ applies the EQ predicate on the "last_complete_at" field.
func LastCompleteAtEQ(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldLastCompleteAt, v))
}

// LastCompleteAtNEQ applies the NEQ predicate on the "last_complete_at" field.
func LastCompleteAtNEQ(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldLastCompleteAt, v))
}

// LastCompleteAtIn applies the In predicate on the "last_complete_at" field.
func LastCompleteAtIn(vs ...time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldLastCompleteAt, vs...))
}

// LastCompleteAtNotIn applies the NotIn predicate on the "last_complete_at" field.
func LastCompleteAtNotIn(vs ...time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldLastCompleteAt, vs...))
}

// LastCompleteAtGT applies the GT predicate on the "last_complete_at" field.
func LastCompleteAtGT(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldLastCompleteAt, v))
}

// LastCompleteAtGTE applies the GTE predicate on the "last_complete_at" field.
func LastCompleteAtGTE(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldLastCompleteAt, v))
}

// LastCompleteAtLT applies the LT predicate on the "last_complete_at" field.
func LastCompleteAtLT(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldLastCompleteAt, v))
}

// LastCompleteAtLTE applies the LTE predicate on the "last_complete_at" field.
func LastCompleteAtLTE(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldLastCompleteAt, v))
}

// LastCompleteAtIsNil applies the IsNil predicate on the "last_complete_at" field.
func LastCompleteAtIsNil() predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIsNull(FieldLastCompleteAt))
}

// LastCompleteAtNotNil applies the NotNil predicate on the "last_complete_at" field.
func LastCompleteAtNotNil() predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotNull(FieldLastCompleteAt))
}

// HealthStatusEQ applies the EQ predicate on the "health_status" field.
func HealthStatusEQ(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldHealthStatus, v))
}

// HealthStatusNEQ applies the NEQ predicate on the "health_status" field.
func HealthStatusNEQ(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldHealthStatus, v))
}

// HealthStatusIn applies the In predicate on the "health_status" field.
func HealthStatusIn(vs ...string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldHealthStatus, vs...))
}

// HealthStatusNotIn applies the NotIn predicate on the "health_status" field.
func HealthStatusNotIn(vs ...string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldHealthStatus, vs...))
}

// HealthStatusGT applies the GT predicate on the "health_status" field.
func HealthStatusGT(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldHealthStatus, v))
}

// HealthStatusGTE applies the GTE predicate on the "health_status" field.
func HealthStatusGTE(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldHealthStatus, v))
}

// HealthStatusLT applies the LT predicate on the "health_status" field.
func HealthStatusLT(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldHealthStatus, v))
}

// HealthStatusLTE applies the LTE predicate on the "health_status" field.
func HealthStatusLTE(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldHealthStatus, v))
}

// HealthStatusContains applies the Contains predicate on the "health_status" field.
func HealthStatusContains(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldContains(FieldHealthStatus, v))
}

// HealthStatusHasPrefix applies the HasPrefix predicate on the "health_status" field.
func HealthStatusHasPrefix(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldHasPrefix(FieldHealthStatus, v))
}

// HealthStatusHasSuffix applies the HasSuffix predicate on the "health_status" field.
func HealthStatusHasSuffix(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldHasSuffix(FieldHealthStatus, v))
}

// HealthStatusEqualFold applies the EqualFold predicate on the "health_status" field.
func HealthStatusEqualFold(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEqualFold(FieldHealthStatus, v))
}

// HealthStatusContainsFold applies the ContainsFold predicate on the "health_status" field.
func HealthStatusContainsFold(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldContainsFold(FieldHealthStatus, v))
}

// KnownCreditCountEQ applies the EQ predicate on the "known_credit_count" field.
func KnownCreditCountEQ(v int) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldKnownCreditCount, v))
}

// KnownCreditCountNEQ applies the NEQ predicate on the "known_credit_count" field.
func KnownCreditCountNEQ(v int) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldKnownCreditCount, v))
}

// KnownCreditCountIn applies the In predicate on the "known_credit_count" field.
func KnownCreditCountIn(vs ...int) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldKnownCreditCount, vs...))
}

// KnownCreditCountNotIn applies the NotIn predicate on the "known_credit_count" field.
func KnownCreditCountNotIn(vs ...int) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldKnownCreditCount, vs...))
}

// KnownCreditCountGT applies the GT predicate on the "known_credit_count" field.
func KnownCreditCountGT(v int) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldKnownCreditCount, v))
}

// KnownCreditCountGTE applies the GTE predicate on the "known_credit_count" field.
func KnownCreditCountGTE(v int) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldKnownCreditCount, v))
}

// KnownCreditCountLT applies the LT predicate on the "known_credit_count" field.
func KnownCreditCountLT(v int) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldKnownCreditCount, v))
}

// KnownCreditCountLTE applies the LTE predicate on the "known_credit_count" field.
func KnownCreditCountLTE(v int) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldKnownCreditCount, v))
}

// IncompleteReasonEQ applies the EQ predicate on the "incomplete_reason" field.
func IncompleteReasonEQ(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldIncompleteReason, v))
}

// IncompleteReasonNEQ applies the NEQ predicate on the "incomplete_reason" field.
func IncompleteReasonNEQ(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldIncompleteReason, v))
}

// IncompleteReasonIn applies the In predicate on the "incomplete_reason" field.
func IncompleteReasonIn(vs ...string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldIncompleteReason, vs...))
}

// IncompleteReasonNotIn applies the NotIn predicate on the "incomplete_reason" field.
func IncompleteReasonNotIn(vs ...string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldIncompleteReason, vs...))
}

// IncompleteReasonGT applies the GT predicate on the "incomplete_reason" field.
func IncompleteReasonGT(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldIncompleteReason, v))
}

// IncompleteReasonGTE applies the GTE predicate on the "incomplete_reason" field.
func IncompleteReasonGTE(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldIncompleteReason, v))
}

// IncompleteReasonLT applies the LT predicate on the "incomplete_reason" field.
func IncompleteReasonLT(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldIncompleteReason, v))
}

// IncompleteReasonLTE applies the LTE predicate on the "incomplete_reason" field.
func IncompleteReasonLTE(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldIncompleteReason, v))
}

// IncompleteReasonContains applies the Contains predicate on the "incomplete_reason" field.
func IncompleteReasonContains(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldContains(FieldIncompleteReason, v))
}

// IncompleteReasonHasPrefix applies the HasPrefix predicate on the "incomplete_reason" field.
func IncompleteReasonHasPrefix(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldHasPrefix(FieldIncompleteReason, v))
}

// IncompleteReasonHasSuffix applies the HasSuffix predicate on the "incomplete_reason" field.
func IncompleteReasonHasSuffix(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldHasSuffix(FieldIncompleteReason, v))
}

// IncompleteReasonIsNil applies the IsNil predicate on the "incomplete_reason" field.
func IncompleteReasonIsNil() predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIsNull(FieldIncompleteReason))
}

// IncompleteReasonNotNil applies the NotNil predicate on the "incomplete_reason" field.
func IncompleteReasonNotNil() predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotNull(FieldIncompleteReason))
}

// IncompleteReasonEqualFold applies the EqualFold predicate on the "incomplete_reason" field.
func IncompleteReasonEqualFold(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEqualFold(FieldIncompleteReason, v))
}

// IncompleteReasonContainsFold applies the ContainsFold predicate on the "incomplete_reason" field.
func IncompleteReasonContainsFold(v string) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldContainsFold(FieldIncompleteReason, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int64) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldRevision, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CarpoolResetAccountState) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CarpoolResetAccountState) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarpoolResetAccountState) predicate.CarpoolResetAccountState {
	return predicate.CarpoolResetAccountState(sql.NotPredicates(p))
}
