// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolresetbatch"
)

// CarpoolResetBatchCreate is the builder for creating a CarpoolResetBatch entity.
type CarpoolResetBatchCreate struct {
	config
	mutation *CarpoolResetBatchMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScopeID sets the "scope_id" field.
func (_c *CarpoolResetBatchCreate) SetScopeID(v int64) *CarpoolResetBatchCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CarpoolResetBatchCreate) SetStatus(v string) *CarpoolResetBatchCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetDetectedAt sets the "detected_at" field.
func (_c *CarpoolResetBatchCreate) SetDetectedAt(v time.Time) *CarpoolResetBatchCreate {
	_c.mutation.SetDetectedAt(v)
	return _c
}

// SetQualifiedAt sets the "qualified_at" field.
func (_c *CarpoolResetBatchCreate) SetQualifiedAt(v time.Time) *CarpoolResetBatchCreate {
	_c.mutation.SetQualifiedAt(v)
	return _c
}

// SetNillableQualifiedAt sets the "qualified_at" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableQualifiedAt(v *time.Time) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetQualifiedAt(*v)
	}
	return _c
}

// SetSlotAt sets the "slot_at" field.
func (_c *CarpoolResetBatchCreate) SetSlotAt(v time.Time) *CarpoolResetBatchCreate {
	_c.mutation.SetSlotAt(v)
	return _c
}

// SetNillableSlotAt sets the "slot_at" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableSlotAt(v *time.Time) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetSlotAt(*v)
	}
	return _c
}

// SetScheduledAt sets the "scheduled_at" field.
func (_c *CarpoolResetBatchCreate) SetScheduledAt(v time.Time) *CarpoolResetBatchCreate {
	_c.mutation.SetScheduledAt(v)
	return _c
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableScheduledAt(v *time.Time) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetScheduledAt(*v)
	}
	return _c
}

// SetScheduleRevision sets the "schedule_revision" field.
func (_c *CarpoolResetBatchCreate) SetScheduleRevision(v int) *CarpoolResetBatchCreate {
	_c.mutation.SetScheduleRevision(v)
	return _c
}

// SetNillableScheduleRevision sets the "schedule_revision" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableScheduleRevision(v *int) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetScheduleRevision(*v)
	}
	return _c
}

// SetEffectiveAt sets the "effective_at" field.
func (_c *CarpoolResetBatchCreate) SetEffectiveAt(v time.Time) *CarpoolResetBatchCreate {
	_c.mutation.SetEffectiveAt(v)
	return _c
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableEffectiveAt(v *time.Time) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetEffectiveAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *CarpoolResetBatchCreate) SetCompletedAt(v time.Time) *CarpoolResetBatchCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableCompletedAt(v *time.Time) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetDelayReason sets the "delay_reason" field.
func (_c *CarpoolResetBatchCreate) SetDelayReason(v string) *CarpoolResetBatchCreate {
	_c.mutation.SetDelayReason(v)
	return _c
}

// SetNillableDelayReason sets the "delay_reason" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableDelayReason(v *string) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetDelayReason(*v)
	}
	return _c
}

// SetEvidence sets the "evidence" field.
func (_c *CarpoolResetBatchCreate) SetEvidence(v map[string]interface{}) *CarpoolResetBatchCreate {
	_c.mutation.SetEvidence(v)
	return _c
}

// SetAnnouncementState sets the "announcement_state" field.
func (_c *CarpoolResetBatchCreate) SetAnnouncementState(v string) *CarpoolResetBatchCreate {
	_c.mutation.SetAnnouncementState(v)
	return _c
}

// SetNillableAnnouncementState sets the "announcement_state" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableAnnouncementState(v *string) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetAnnouncementState(*v)
	}
	return _c
}

// SetQualificationSource sets the "qualification_source" field.
func (_c *CarpoolResetBatchCreate) SetQualificationSource(v string) *CarpoolResetBatchCreate {
	_c.mutation.SetQualificationSource(v)
	return _c
}

// SetSourceEventKeyHash sets the "source_event_key_hash" field.
func (_c *CarpoolResetBatchCreate) SetSourceEventKeyHash(v string) *CarpoolResetBatchCreate {
	_c.mutation.SetSourceEventKeyHash(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CarpoolResetBatchCreate) SetCreatedAt(v time.Time) *CarpoolResetBatchCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableCreatedAt(v *time.Time) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CarpoolResetBatchCreate) SetUpdatedAt(v time.Time) *CarpoolResetBatchCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CarpoolResetBatchCreate) SetNillableUpdatedAt(v *time.Time) *CarpoolResetBatchCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CarpoolResetBatchMutation object of the builder.
func (_c *CarpoolResetBatchCreate) Mutation() *CarpoolResetBatchMutation {
	return _c.mutation
}

// Save creates the CarpoolResetBatch in the database.
func (_c *CarpoolResetBatchCreate) Save(ctx context.Context) (*CarpoolResetBatch, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarpoolResetBatchCreate) SaveX(ctx context.Context) *CarpoolResetBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolResetBatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolResetBatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarpoolResetBatchCreate) defaults() {
	if _, ok := _c.mutation.ScheduleRevision(); !ok {
		v := carpoolresetbatch.DefaultScheduleRevision
		_c.mutation.SetScheduleRevision(v)
	}
	if _, ok := _c.mutation.Evidence(); !ok {
		v := carpoolresetbatch.DefaultEvidence()
		_c.mutation.SetEvidence(v)
	}
	if _, ok := _c.mutation.AnnouncementState(); !ok {
		v := carpoolresetbatch.DefaultAnnouncementState
		_c.mutation.SetAnnouncementState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := carpoolresetbatch.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := carpoolresetbatch.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarpoolResetBatchCreate) check() error {
	if _, ok := _c.mutation.ScopeID(); !ok {
		return &ValidationError{Name: "scope_id", err: errors.New(`ent: missing required field "CarpoolResetBatch.scope_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CarpoolResetBatch.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := carpoolresetbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CarpoolResetBatch.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DetectedAt(); !ok {
		return &ValidationError{Name: "detected_at", err: errors.New(`ent: missing required field "CarpoolResetBatch.detected_at"`)}
	}
	if _, ok := _c.mutation.ScheduleRevision(); !ok {
		return &ValidationError{Name: "schedule_revision", err: errors.New(`ent: missing required field "CarpoolResetBatch.schedule_revision"`)}
	}
	if _, ok := _c.mutation.Evidence(); !ok {
		return &ValidationError{Name: "evidence", err: errors.New(`ent: missing required field "CarpoolResetBatch.evidence"`)}
	}
	if _, ok := _c.mutation.AnnouncementState(); !ok {
		return &ValidationError{Name: "announcement_state", err: errors.New(`ent: missing required field "CarpoolResetBatch.announcement_state"`)}
	}
	if v, ok := _c.mutation.AnnouncementState(); ok {
		if err := carpoolresetbatch.AnnouncementStateValidator(v); err != nil {
			return &ValidationError{Name: "announcement_state", err: fmt.Errorf(`ent: validator failed for field "CarpoolResetBatch.announcement_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QualificationSource(); !ok {
		return &ValidationError{Name: "qualification_source", err: errors.New(`ent: missing required field "CarpoolResetBatch.qualification_source"`)}
	}
	if v, ok := _c.mutation.QualificationSource(); ok {
		if err := carpoolresetbatch.QualificationSourceValidator(v); err != nil {
			return &ValidationError{Name: "qualification_source", err: fmt.Errorf(`ent: validator failed for field "CarpoolResetBatch.qualification_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceEventKeyHash(); !ok {
		return &ValidationError{Name: "source_event_key_hash", err: errors.New(`ent: missing required field "CarpoolResetBatch.source_event_key_hash"`)}
	}
	if v, ok := _c.mutation.SourceEventKeyHash(); ok {
		if err := carpoolresetbatch.SourceEventKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "source_event_key_hash", err: fmt.Errorf(`ent: validator failed for field "CarpoolResetBatch.source_event_key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CarpoolResetBatch.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CarpoolResetBatch.updated_at"`)}
	}
	return nil
}

func (_c *CarpoolResetBatchCreate) sqlSave(ctx context.Context) (*CarpoolResetBatch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarpoolResetBatchCreate) createSpec() (*CarpoolResetBatch, *sqlgraph.CreateSpec) {
	var (
		_node = &CarpoolResetBatch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carpoolresetbatch.Table, sqlgraph.NewFieldSpec(carpoolresetbatch.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(carpoolresetbatch.FieldScopeID, field.TypeInt64, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(carpoolresetbatch.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DetectedAt(); ok {
		_spec.SetField(carpoolresetbatch.FieldDetectedAt, field.TypeTime, value)
		_node.DetectedAt = value
	}
	if value, ok := _c.mutation.QualifiedAt(); ok {
		_spec.SetField(carpoolresetbatch.FieldQualifiedAt, field.TypeTime, value)
		_node.QualifiedAt = &value
	}
	if value, ok := _c.mutation.SlotAt(); ok {
		_spec.SetField(carpoolresetbatch.FieldSlotAt, field.TypeTime, value)
		_node.SlotAt = &value
	}
	if value, ok := _c.mutation.ScheduledAt(); ok {
		_spec.SetField(carpoolresetbatch.FieldScheduledAt, field.TypeTime, value)
		_node.ScheduledAt = &value
	}
	if value, ok := _c.mutation.ScheduleRevision(); ok {
		_spec.SetField(carpoolresetbatch.FieldScheduleRevision, field.TypeInt, value)
		_node.ScheduleRevision = value
	}
	if value, ok := _c.mutation.EffectiveAt(); ok {
		_spec.SetField(carpoolresetbatch.FieldEffectiveAt, field.TypeTime, value)
		_node.EffectiveAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(carpoolresetbatch.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.DelayReason(); ok {
		_spec.SetField(carpoolresetbatch.FieldDelayReason, field.TypeString, value)
		_node.DelayReason = &value
	}
	if value, ok := _c.mutation.Evidence(); ok {
		_spec.SetField(carpoolresetbatch.FieldEvidence, field.TypeJSON, value)
		_node.Evidence = value
	}
	if value, ok := _c.mutation.AnnouncementState(); ok {
		_spec.SetField(carpoolresetbatch.FieldAnnouncementState, field.TypeString, value)
		_node.AnnouncementState = value
	}
	if value, ok := _c.mutation.QualificationSource(); ok {
		_spec.SetField(carpoolresetbatch.FieldQualificationSource, field.TypeString, value)
		_node.QualificationSource = value
	}
	if value, ok := _c.mutation.SourceEventKeyHash(); ok {
		_spec.SetField(carpoolresetbatch.FieldSourceEventKeyHash, field.TypeString, value)
		_node.SourceEventKeyHash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carpoolresetbatch.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolresetbatch.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolResetBatch.Create().
//		SetScopeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolResetBatchUpsert) {
//			SetScopeID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolResetBatchCreate) OnConflict(opts ...sql.ConflictOption) *CarpoolResetBatchUpsertOne {
	_c.conflict = opts
	return &CarpoolResetBatchUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolResetBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolResetBatchCreate) OnConflictColumns(columns ...string) *CarpoolResetBatchUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolResetBatchUpsertOne{
		create: _c,
	}
}

type (
	// CarpoolResetBatchUpsertOne is the builder for "upsert"-ing
	//  one CarpoolResetBatch node.
	CarpoolResetBatchUpsertOne struct {
		create *CarpoolResetBatchCreate
	}

	// CarpoolResetBatchUpsert is the "OnConflict" setter.
	CarpoolResetBatchUpsert struct {
		*sql.UpdateSet
	}
)

// SetScopeID sets the "scope_id" field.
func (u *CarpoolResetBatchUpsert) SetScopeID(v int64) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateScopeID() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldScopeID)
	return u
}

// AddScopeID adds v to the "scope_id" field.
func (u *CarpoolResetBatchUpsert) AddScopeID(v int64) *CarpoolResetBatchUpsert {
	u.Add(carpoolresetbatch.FieldScopeID, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CarpoolResetBatchUpsert) SetStatus(v string) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateStatus() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldStatus)
	return u
}

// SetDetectedAt sets the "detected_at" field.
func (u *CarpoolResetBatchUpsert) SetDetectedAt(v time.Time) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldDetectedAt, v)
	return u
}

// UpdateDetectedAt sets the "detected_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateDetectedAt() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldDetectedAt)
	return u
}

// SetQualifiedAt sets the "qualified_at" field.
func (u *CarpoolResetBatchUpsert) SetQualifiedAt(v time.Time) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldQualifiedAt, v)
	return u
}

// UpdateQualifiedAt sets the "qualified_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateQualifiedAt() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldQualifiedAt)
	return u
}

// ClearQualifiedAt clears the value of the "qualified_at" field.
func (u *CarpoolResetBatchUpsert) ClearQualifiedAt() *CarpoolResetBatchUpsert {
	u.SetNull(carpoolresetbatch.FieldQualifiedAt)
	return u
}

// SetSlotAt sets the "slot_at" field.
func (u *CarpoolResetBatchUpsert) SetSlotAt(v time.Time) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldSlotAt, v)
	return u
}

// UpdateSlotAt sets the "slot_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateSlotAt() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldSlotAt)
	return u
}

// ClearSlotAt clears the value of the "slot_at" field.
func (u *CarpoolResetBatchUpsert) ClearSlotAt() *CarpoolResetBatchUpsert {
	u.SetNull(carpoolresetbatch.FieldSlotAt)
	return u
}

// SetScheduledAt sets the "scheduled_at" field.
func (u *CarpoolResetBatchUpsert) SetScheduledAt(v time.Time) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldScheduledAt, v)
	return u
}

// UpdateScheduledAt sets the "scheduled_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateScheduledAt() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldScheduledAt)
	return u
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (u *CarpoolResetBatchUpsert) ClearScheduledAt() *CarpoolResetBatchUpsert {
	u.SetNull(carpoolresetbatch.FieldScheduledAt)
	return u
}

// SetScheduleRevision sets the "schedule_revision" field.
func (u *CarpoolResetBatchUpsert) SetScheduleRevision(v int) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldScheduleRevision, v)
	return u
}

// UpdateScheduleRevision sets the "schedule_revision" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateScheduleRevision() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldScheduleRevision)
	return u
}

// AddScheduleRevision adds v to the "schedule_revision" field.
func (u *CarpoolResetBatchUpsert) AddScheduleRevision(v int) *CarpoolResetBatchUpsert {
	u.Add(carpoolresetbatch.FieldScheduleRevision, v)
	return u
}

// SetEffectiveAt sets the "effective_at" field.
func (u *CarpoolResetBatchUpsert) SetEffectiveAt(v time.Time) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldEffectiveAt, v)
	return u
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateEffectiveAt() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldEffectiveAt)
	return u
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (u *CarpoolResetBatchUpsert) ClearEffectiveAt() *CarpoolResetBatchUpsert {
	u.SetNull(carpoolresetbatch.FieldEffectiveAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *CarpoolResetBatchUpsert) SetCompletedAt(v time.Time) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateCompletedAt() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *CarpoolResetBatchUpsert) ClearCompletedAt() *CarpoolResetBatchUpsert {
	u.SetNull(carpoolresetbatch.FieldCompletedAt)
	return u
}

// SetDelayReason sets the "delay_reason" field.
func (u *CarpoolResetBatchUpsert) SetDelayReason(v string) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldDelayReason, v)
	return u
}

// UpdateDelayReason sets the "delay_reason" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateDelayReason() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldDelayReason)
	return u
}

// ClearDelayReason clears the value of the "delay_reason" field.
func (u *CarpoolResetBatchUpsert) ClearDelayReason() *CarpoolResetBatchUpsert {
	u.SetNull(carpoolresetbatch.FieldDelayReason)
	return u
}

// SetEvidence sets the "evidence" field.
func (u *CarpoolResetBatchUpsert) SetEvidence(v map[string]interface{}) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldEvidence, v)
	return u
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateEvidence() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldEvidence)
	return u
}

// SetAnnouncementState sets the "announcement_state" field.
func (u *CarpoolResetBatchUpsert) SetAnnouncementState(v string) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldAnnouncementState, v)
	return u
}

// UpdateAnnouncementState sets the "announcement_state" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateAnnouncementState() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldAnnouncementState)
	return u
}

// SetQualificationSource sets the "qualification_source" field.
func (u *CarpoolResetBatchUpsert) SetQualificationSource(v string) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldQualificationSource, v)
	return u
}

// UpdateQualificationSource sets the "qualification_source" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateQualificationSource() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldQualificationSource)
	return u
}

// SetSourceEventKeyHash sets the "source_event_key_hash" field.
func (u *CarpoolResetBatchUpsert) SetSourceEventKeyHash(v string) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldSourceEventKeyHash, v)
	return u
}

// UpdateSourceEventKeyHash sets the "source_event_key_hash" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateSourceEventKeyHash() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldSourceEventKeyHash)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolResetBatchUpsert) SetUpdatedAt(v time.Time) *CarpoolResetBatchUpsert {
	u.Set(carpoolresetbatch.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsert) UpdateUpdatedAt() *CarpoolResetBatchUpsert {
	u.SetExcluded(carpoolresetbatch.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CarpoolResetBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolResetBatchUpsertOne) UpdateNewValues() *CarpoolResetBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(carpoolresetbatch.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolResetBatch.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarpoolResetBatchUpsertOne) Ignore() *CarpoolResetBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolResetBatchUpsertOne) DoNothing() *CarpoolResetBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolResetBatchCreate.OnConflict
// documentation for more info.
func (u *CarpoolResetBatchUpsertOne) Update(set func(*CarpoolResetBatchUpsert)) *CarpoolResetBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolResetBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *CarpoolResetBatchUpsertOne) SetScopeID(v int64) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetScopeID(v)
	})
}

// AddScopeID adds v to the "scope_id" field.
func (u *CarpoolResetBatchUpsertOne) AddScopeID(v int64) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.AddScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateScopeID() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateScopeID()
	})
}

// SetStatus sets the "status" field.
func (u *CarpoolResetBatchUpsertOne) SetStatus(v string) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateStatus() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetDetectedAt sets the "detected_at" field.
func (u *CarpoolResetBatchUpsertOne) SetDetectedAt(v time.Time) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetDetectedAt(v)
	})
}

// UpdateDetectedAt sets the "detected_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateDetectedAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateDetectedAt()
	})
}

// SetQualifiedAt sets the "qualified_at" field.
func (u *CarpoolResetBatchUpsertOne) SetQualifiedAt(v time.Time) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetQualifiedAt(v)
	})
}

// UpdateQualifiedAt sets the "qualified_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateQualifiedAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateQualifiedAt()
	})
}

// ClearQualifiedAt clears the value of the "qualified_at" field.
func (u *CarpoolResetBatchUpsertOne) ClearQualifiedAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearQualifiedAt()
	})
}

// SetSlotAt sets the "slot_at" field.
func (u *CarpoolResetBatchUpsertOne) SetSlotAt(v time.Time) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetSlotAt(v)
	})
}

// UpdateSlotAt sets the "slot_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateSlotAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateSlotAt()
	})
}

// ClearSlotAt clears the value of the "slot_at" field.
func (u *CarpoolResetBatchUpsertOne) ClearSlotAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearSlotAt()
	})
}

// SetScheduledAt sets the "scheduled_at" field.
func (u *CarpoolResetBatchUpsertOne) SetScheduledAt(v time.Time) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetScheduledAt(v)
	})
}

// UpdateScheduledAt sets the "scheduled_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateScheduledAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateScheduledAt()
	})
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (u *CarpoolResetBatchUpsertOne) ClearScheduledAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearScheduledAt()
	})
}

// SetScheduleRevision sets the "schedule_revision" field.
func (u *CarpoolResetBatchUpsertOne) SetScheduleRevision(v int) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetScheduleRevision(v)
	})
}

// AddScheduleRevision adds v to the "schedule_revision" field.
func (u *CarpoolResetBatchUpsertOne) AddScheduleRevision(v int) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.AddScheduleRevision(v)
	})
}

// UpdateScheduleRevision sets the "schedule_revision" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateScheduleRevision() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateScheduleRevision()
	})
}

// SetEffectiveAt sets the "effective_at" field.
func (u *CarpoolResetBatchUpsertOne) SetEffectiveAt(v time.Time) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetEffectiveAt(v)
	})
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateEffectiveAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateEffectiveAt()
	})
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (u *CarpoolResetBatchUpsertOne) ClearEffectiveAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearEffectiveAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *CarpoolResetBatchUpsertOne) SetCompletedAt(v time.Time) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateCompletedAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *CarpoolResetBatchUpsertOne) ClearCompletedAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearCompletedAt()
	})
}

// SetDelayReason sets the "delay_reason" field.
func (u *CarpoolResetBatchUpsertOne) SetDelayReason(v string) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetDelayReason(v)
	})
}

// UpdateDelayReason sets the "delay_reason" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateDelayReason() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateDelayReason()
	})
}

// ClearDelayReason clears the value of the "delay_reason" field.
func (u *CarpoolResetBatchUpsertOne) ClearDelayReason() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearDelayReason()
	})
}

// SetEvidence sets the "evidence" field.
func (u *CarpoolResetBatchUpsertOne) SetEvidence(v map[string]interface{}) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetEvidence(v)
	})
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateEvidence() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateEvidence()
	})
}

// SetAnnouncementState sets the "announcement_state" field.
func (u *CarpoolResetBatchUpsertOne) SetAnnouncementState(v string) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetAnnouncementState(v)
	})
}

// UpdateAnnouncementState sets the "announcement_state" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateAnnouncementState() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateAnnouncementState()
	})
}

// SetQualificationSource sets the "qualification_source" field.
func (u *CarpoolResetBatchUpsertOne) SetQualificationSource(v string) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetQualificationSource(v)
	})
}

// UpdateQualificationSource sets the "qualification_source" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateQualificationSource() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateQualificationSource()
	})
}

// SetSourceEventKeyHash sets the "source_event_key_hash" field.
func (u *CarpoolResetBatchUpsertOne) SetSourceEventKeyHash(v string) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetSourceEventKeyHash(v)
	})
}

// UpdateSourceEventKeyHash sets the "source_event_key_hash" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateSourceEventKeyHash() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateSourceEventKeyHash()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolResetBatchUpsertOne) SetUpdatedAt(v time.Time) *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertOne) UpdateUpdatedAt() *CarpoolResetBatchUpsertOne {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolResetBatchUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolResetBatchCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolResetBatchUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarpoolResetBatchUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarpoolResetBatchUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarpoolResetBatchCreateBulk is the builder for creating many CarpoolResetBatch entities in bulk.
type CarpoolResetBatchCreateBulk struct {
	config
	err      error
	builders []*CarpoolResetBatchCreate
	conflict []sql.ConflictOption
}

// Save creates the CarpoolResetBatch entities in the database.
func (_c *CarpoolResetBatchCreateBulk) Save(ctx context.Context) ([]*CarpoolResetBatch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarpoolResetBatch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarpoolResetBatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarpoolResetBatchCreateBulk) SaveX(ctx context.Context) []*CarpoolResetBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolResetBatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolResetBatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolResetBatch.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolResetBatchUpsert) {
//			SetScopeID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolResetBatchCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarpoolResetBatchUpsertBulk {
	_c.conflict = opts
	return &CarpoolResetBatchUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolResetBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolResetBatchCreateBulk) OnConflictColumns(columns ...string) *CarpoolResetBatchUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolResetBatchUpsertBulk{
		create: _c,
	}
}

// CarpoolResetBatchUpsertBulk is the builder for "upsert"-ing
// a bulk of CarpoolResetBatch nodes.
type CarpoolResetBatchUpsertBulk struct {
	create *CarpoolResetBatchCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarpoolResetBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolResetBatchUpsertBulk) UpdateNewValues() *CarpoolResetBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(carpoolresetbatch.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolResetBatch.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarpoolResetBatchUpsertBulk) Ignore() *CarpoolResetBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolResetBatchUpsertBulk) DoNothing() *CarpoolResetBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolResetBatchCreateBulk.OnConflict
// documentation for more info.
func (u *CarpoolResetBatchUpsertBulk) Update(set func(*CarpoolResetBatchUpsert)) *CarpoolResetBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolResetBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *CarpoolResetBatchUpsertBulk) SetScopeID(v int64) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetScopeID(v)
	})
}

// AddScopeID adds v to the "scope_id" field.
func (u *CarpoolResetBatchUpsertBulk) AddScopeID(v int64) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.AddScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateScopeID() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateScopeID()
	})
}

// SetStatus sets the "status" field.
func (u *CarpoolResetBatchUpsertBulk) SetStatus(v string) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateStatus() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetDetectedAt sets the "detected_at" field.
func (u *CarpoolResetBatchUpsertBulk) SetDetectedAt(v time.Time) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetDetectedAt(v)
	})
}

// UpdateDetectedAt sets the "detected_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateDetectedAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateDetectedAt()
	})
}

// SetQualifiedAt sets the "qualified_at" field.
func (u *CarpoolResetBatchUpsertBulk) SetQualifiedAt(v time.Time) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetQualifiedAt(v)
	})
}

// UpdateQualifiedAt sets the "qualified_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateQualifiedAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateQualifiedAt()
	})
}

// ClearQualifiedAt clears the value of the "qualified_at" field.
func (u *CarpoolResetBatchUpsertBulk) ClearQualifiedAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearQualifiedAt()
	})
}

// SetSlotAt sets the "slot_at" field.
func (u *CarpoolResetBatchUpsertBulk) SetSlotAt(v time.Time) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetSlotAt(v)
	})
}

// UpdateSlotAt sets the "slot_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateSlotAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateSlotAt()
	})
}

// ClearSlotAt clears the value of the "slot_at" field.
func (u *CarpoolResetBatchUpsertBulk) ClearSlotAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearSlotAt()
	})
}

// SetScheduledAt sets the "scheduled_at" field.
func (u *CarpoolResetBatchUpsertBulk) SetScheduledAt(v time.Time) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetScheduledAt(v)
	})
}

// UpdateScheduledAt sets the "scheduled_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateScheduledAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateScheduledAt()
	})
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (u *CarpoolResetBatchUpsertBulk) ClearScheduledAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearScheduledAt()
	})
}

// SetScheduleRevision sets the "schedule_revision" field.
func (u *CarpoolResetBatchUpsertBulk) SetScheduleRevision(v int) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetScheduleRevision(v)
	})
}

// AddScheduleRevision adds v to the "schedule_revision" field.
func (u *CarpoolResetBatchUpsertBulk) AddScheduleRevision(v int) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.AddScheduleRevision(v)
	})
}

// UpdateScheduleRevision sets the "schedule_revision" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateScheduleRevision() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateScheduleRevision()
	})
}

// SetEffectiveAt sets the "effective_at" field.
func (u *CarpoolResetBatchUpsertBulk) SetEffectiveAt(v time.Time) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetEffectiveAt(v)
	})
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateEffectiveAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateEffectiveAt()
	})
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (u *CarpoolResetBatchUpsertBulk) ClearEffectiveAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearEffectiveAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *CarpoolResetBatchUpsertBulk) SetCompletedAt(v time.Time) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateCompletedAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *CarpoolResetBatchUpsertBulk) ClearCompletedAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearCompletedAt()
	})
}

// SetDelayReason sets the "delay_reason" field.
func (u *CarpoolResetBatchUpsertBulk) SetDelayReason(v string) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetDelayReason(v)
	})
}

// UpdateDelayReason sets the "delay_reason" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateDelayReason() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateDelayReason()
	})
}

// ClearDelayReason clears the value of the "delay_reason" field.
func (u *CarpoolResetBatchUpsertBulk) ClearDelayReason() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.ClearDelayReason()
	})
}

// SetEvidence sets the "evidence" field.
func (u *CarpoolResetBatchUpsertBulk) SetEvidence(v map[string]interface{}) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetEvidence(v)
	})
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateEvidence() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateEvidence()
	})
}

// SetAnnouncementState sets the "announcement_state" field.
func (u *CarpoolResetBatchUpsertBulk) SetAnnouncementState(v string) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetAnnouncementState(v)
	})
}

// UpdateAnnouncementState sets the "announcement_state" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateAnnouncementState() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateAnnouncementState()
	})
}

// SetQualificationSource sets the "qualification_source" field.
func (u *CarpoolResetBatchUpsertBulk) SetQualificationSource(v string) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetQualificationSource(v)
	})
}

// UpdateQualificationSource sets the "qualification_source" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateQualificationSource() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateQualificationSource()
	})
}

// SetSourceEventKeyHash sets the "source_event_key_hash" field.
func (u *CarpoolResetBatchUpsertBulk) SetSourceEventKeyHash(v string) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetSourceEventKeyHash(v)
	})
}

// UpdateSourceEventKeyHash sets the "source_event_key_hash" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateSourceEventKeyHash() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateSourceEventKeyHash()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolResetBatchUpsertBulk) SetUpdatedAt(v time.Time) *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolResetBatchUpsertBulk) UpdateUpdatedAt() *CarpoolResetBatchUpsertBulk {
	return u.Update(func(s *CarpoolResetBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolResetBatchUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarpoolResetBatchCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolResetBatchCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolResetBatchUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
