// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolterm"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CarpoolTermUpdate is the builder for updating CarpoolTerm entities.
type CarpoolTermUpdate struct {
	config
	hooks    []Hook
	mutation *CarpoolTermMutation
}

// Where appends a list predicates to the CarpoolTermUpdate builder.
func (_u *CarpoolTermUpdate) Where(ps ...predicate.CarpoolTerm) *CarpoolTermUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CarpoolTermUpdate) SetUserID(v int64) *CarpoolTermUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableUserID(v *int64) *CarpoolTermUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CarpoolTermUpdate) AddUserID(v int64) *CarpoolTermUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *CarpoolTermUpdate) SetScopeID(v int64) *CarpoolTermUpdate {
	_u.mutation.ResetScopeID()
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableScopeID(v *int64) *CarpoolTermUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// AddScopeID adds value to the "scope_id" field.
func (_u *CarpoolTermUpdate) AddScopeID(v int64) *CarpoolTermUpdate {
	_u.mutation.AddScopeID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *CarpoolTermUpdate) SetGroupID(v int64) *CarpoolTermUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableGroupID(v *int64) *CarpoolTermUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *CarpoolTermUpdate) AddGroupID(v int64) *CarpoolTermUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *CarpoolTermUpdate) SetPlanID(v int64) *CarpoolTermUpdate {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillablePlanID(v *int64) *CarpoolTermUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *CarpoolTermUpdate) AddPlanID(v int64) *CarpoolTermUpdate {
	_u.mutation.AddPlanID(v)
	return _u
}

// SetPlanSnapshot sets the "plan_snapshot" field.
func (_u *CarpoolTermUpdate) SetPlanSnapshot(v map[string]interface{}) *CarpoolTermUpdate {
	_u.mutation.SetPlanSnapshot(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *CarpoolTermUpdate) SetStartsAt(v time.Time) *CarpoolTermUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableStartsAt(v *time.Time) *CarpoolTermUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CarpoolTermUpdate) SetExpiresAt(v time.Time) *CarpoolTermUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableExpiresAt(v *time.Time) *CarpoolTermUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CarpoolTermUpdate) SetStatus(v string) *CarpoolTermUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableStatus(v *string) *CarpoolTermUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBoostUsed sets the "boost_used" field.
func (_u *CarpoolTermUpdate) SetBoostUsed(v int) *CarpoolTermUpdate {
	_u.mutation.ResetBoostUsed()
	_u.mutation.SetBoostUsed(v)
	return _u
}

// SetNillableBoostUsed sets the "boost_used" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableBoostUsed(v *int) *CarpoolTermUpdate {
	if v != nil {
		_u.SetBoostUsed(*v)
	}
	return _u
}

// AddBoostUsed adds value to the "boost_used" field.
func (_u *CarpoolTermUpdate) AddBoostUsed(v int) *CarpoolTermUpdate {
	_u.mutation.AddBoostUsed(v)
	return _u
}

// SetSourceMode sets the "source_mode" field.
func (_u *CarpoolTermUpdate) SetSourceMode(v string) *CarpoolTermUpdate {
	_u.mutation.SetSourceMode(v)
	return _u
}

// SetNillableSourceMode sets the "source_mode" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableSourceMode(v *string) *CarpoolTermUpdate {
	if v != nil {
		_u.SetSourceMode(*v)
	}
	return _u
}

// SetHistoryComplete sets the "history_complete" field.
func (_u *CarpoolTermUpdate) SetHistoryComplete(v bool) *CarpoolTermUpdate {
	_u.mutation.SetHistoryComplete(v)
	return _u
}

// SetNillableHistoryComplete sets the "history_complete" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableHistoryComplete(v *bool) *CarpoolTermUpdate {
	if v != nil {
		_u.SetHistoryComplete(*v)
	}
	return _u
}

// SetStatisticsSince sets the "statistics_since" field.
func (_u *CarpoolTermUpdate) SetStatisticsSince(v time.Time) *CarpoolTermUpdate {
	_u.mutation.SetStatisticsSince(v)
	return _u
}

// SetNillableStatisticsSince sets the "statistics_since" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableStatisticsSince(v *time.Time) *CarpoolTermUpdate {
	if v != nil {
		_u.SetStatisticsSince(*v)
	}
	return _u
}

// ClearStatisticsSince clears the value of the "statistics_since" field.
func (_u *CarpoolTermUpdate) ClearStatisticsSince() *CarpoolTermUpdate {
	_u.mutation.ClearStatisticsSince()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *CarpoolTermUpdate) SetCreatedBy(v int64) *CarpoolTermUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableCreatedBy(v *int64) *CarpoolTermUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *CarpoolTermUpdate) AddCreatedBy(v int64) *CarpoolTermUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CarpoolTermUpdate) SetNotes(v string) *CarpoolTermUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableNotes(v *string) *CarpoolTermUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *CarpoolTermUpdate) ClearNotes() *CarpoolTermUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetTerminatedAt sets the "terminated_at" field.
func (_u *CarpoolTermUpdate) SetTerminatedAt(v time.Time) *CarpoolTermUpdate {
	_u.mutation.SetTerminatedAt(v)
	return _u
}

// SetNillableTerminatedAt sets the "terminated_at" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableTerminatedAt(v *time.Time) *CarpoolTermUpdate {
	if v != nil {
		_u.SetTerminatedAt(*v)
	}
	return _u
}

// ClearTerminatedAt clears the value of the "terminated_at" field.
func (_u *CarpoolTermUpdate) ClearTerminatedAt() *CarpoolTermUpdate {
	_u.mutation.ClearTerminatedAt()
	return _u
}

// SetTerminatedBy sets the "terminated_by" field.
func (_u *CarpoolTermUpdate) SetTerminatedBy(v int64) *CarpoolTermUpdate {
	_u.mutation.ResetTerminatedBy()
	_u.mutation.SetTerminatedBy(v)
	return _u
}

// SetNillableTerminatedBy sets the "terminated_by" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableTerminatedBy(v *int64) *CarpoolTermUpdate {
	if v != nil {
		_u.SetTerminatedBy(*v)
	}
	return _u
}

// AddTerminatedBy adds value to the "terminated_by" field.
func (_u *CarpoolTermUpdate) AddTerminatedBy(v int64) *CarpoolTermUpdate {
	_u.mutation.AddTerminatedBy(v)
	return _u
}

// ClearTerminatedBy clears the value of the "terminated_by" field.
func (_u *CarpoolTermUpdate) ClearTerminatedBy() *CarpoolTermUpdate {
	_u.mutation.ClearTerminatedBy()
	return _u
}

// SetTerminationReason sets the "termination_reason" field.
func (_u *CarpoolTermUpdate) SetTerminationReason(v string) *CarpoolTermUpdate {
	_u.mutation.SetTerminationReason(v)
	return _u
}

// SetNillableTerminationReason sets the "termination_reason" field if the given value is not nil.
func (_u *CarpoolTermUpdate) SetNillableTerminationReason(v *string) *CarpoolTermUpdate {
	if v != nil {
		_u.SetTerminationReason(*v)
	}
	return _u
}

// ClearTerminationReason clears the value of the "termination_reason" field.
func (_u *CarpoolTermUpdate) ClearTerminationReason() *CarpoolTermUpdate {
	_u.mutation.ClearTerminationReason()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CarpoolTermUpdate) SetUpdatedAt(v time.Time) *CarpoolTermUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CarpoolTermMutation object of the builder.
func (_u *CarpoolTermUpdate) Mutation() *CarpoolTermMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CarpoolTermUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CarpoolTermUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CarpoolTermUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CarpoolTermUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CarpoolTermUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carpoolterm.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CarpoolTermUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := carpoolterm.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CarpoolTerm.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceMode(); ok {
		if err := carpoolterm.SourceModeValidator(v); err != nil {
			return &ValidationError{Name: "source_mode", err: fmt.Errorf(`ent: validator failed for field "CarpoolTerm.source_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *CarpoolTermUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carpoolterm.Table, carpoolterm.Columns, sqlgraph.NewFieldSpec(carpoolterm.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(carpoolterm.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(carpoolterm.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(carpoolterm.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScopeID(); ok {
		_spec.AddField(carpoolterm.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(carpoolterm.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(carpoolterm.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(carpoolterm.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(carpoolterm.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlanSnapshot(); ok {
		_spec.SetField(carpoolterm.FieldPlanSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(carpoolterm.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(carpoolterm.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(carpoolterm.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BoostUsed(); ok {
		_spec.SetField(carpoolterm.FieldBoostUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBoostUsed(); ok {
		_spec.AddField(carpoolterm.FieldBoostUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceMode(); ok {
		_spec.SetField(carpoolterm.FieldSourceMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.HistoryComplete(); ok {
		_spec.SetField(carpoolterm.FieldHistoryComplete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatisticsSince(); ok {
		_spec.SetField(carpoolterm.FieldStatisticsSince, field.TypeTime, value)
	}
	if _u.mutation.StatisticsSinceCleared() {
		_spec.ClearField(carpoolterm.FieldStatisticsSince, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(carpoolterm.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(carpoolterm.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(carpoolterm.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(carpoolterm.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.TerminatedAt(); ok {
		_spec.SetField(carpoolterm.FieldTerminatedAt, field.TypeTime, value)
	}
	if _u.mutation.TerminatedAtCleared() {
		_spec.ClearField(carpoolterm.FieldTerminatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TerminatedBy(); ok {
		_spec.SetField(carpoolterm.FieldTerminatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTerminatedBy(); ok {
		_spec.AddField(carpoolterm.FieldTerminatedBy, field.TypeInt64, value)
	}
	if _u.mutation.TerminatedByCleared() {
		_spec.ClearField(carpoolterm.FieldTerminatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.TerminationReason(); ok {
		_spec.SetField(carpoolterm.FieldTerminationReason, field.TypeString, value)
	}
	if _u.mutation.TerminationReasonCleared() {
		_spec.ClearField(carpoolterm.FieldTerminationReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolterm.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carpoolterm.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CarpoolTermUpdateOne is the builder for updating a single CarpoolTerm entity.
type CarpoolTermUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CarpoolTermMutation
}

// SetUserID sets the "user_id" field.
func (_u *CarpoolTermUpdateOne) SetUserID(v int64) *CarpoolTermUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableUserID(v *int64) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CarpoolTermUpdateOne) AddUserID(v int64) *CarpoolTermUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *CarpoolTermUpdateOne) SetScopeID(v int64) *CarpoolTermUpdateOne {
	_u.mutation.ResetScopeID()
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableScopeID(v *int64) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// AddScopeID adds value to the "scope_id" field.
func (_u *CarpoolTermUpdateOne) AddScopeID(v int64) *CarpoolTermUpdateOne {
	_u.mutation.AddScopeID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *CarpoolTermUpdateOne) SetGroupID(v int64) *CarpoolTermUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableGroupID(v *int64) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *CarpoolTermUpdateOne) AddGroupID(v int64) *CarpoolTermUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *CarpoolTermUpdateOne) SetPlanID(v int64) *CarpoolTermUpdateOne {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillablePlanID(v *int64) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *CarpoolTermUpdateOne) AddPlanID(v int64) *CarpoolTermUpdateOne {
	_u.mutation.AddPlanID(v)
	return _u
}

// SetPlanSnapshot sets the "plan_snapshot" field.
func (_u *CarpoolTermUpdateOne) SetPlanSnapshot(v map[string]interface{}) *CarpoolTermUpdateOne {
	_u.mutation.SetPlanSnapshot(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *CarpoolTermUpdateOne) SetStartsAt(v time.Time) *CarpoolTermUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableStartsAt(v *time.Time) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CarpoolTermUpdateOne) SetExpiresAt(v time.Time) *CarpoolTermUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableExpiresAt(v *time.Time) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CarpoolTermUpdateOne) SetStatus(v string) *CarpoolTermUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableStatus(v *string) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBoostUsed sets the "boost_used" field.
func (_u *CarpoolTermUpdateOne) SetBoostUsed(v int) *CarpoolTermUpdateOne {
	_u.mutation.ResetBoostUsed()
	_u.mutation.SetBoostUsed(v)
	return _u
}

// SetNillableBoostUsed sets the "boost_used" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableBoostUsed(v *int) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetBoostUsed(*v)
	}
	return _u
}

// AddBoostUsed adds value to the "boost_used" field.
func (_u *CarpoolTermUpdateOne) AddBoostUsed(v int) *CarpoolTermUpdateOne {
	_u.mutation.AddBoostUsed(v)
	return _u
}

// SetSourceMode sets the "source_mode" field.
func (_u *CarpoolTermUpdateOne) SetSourceMode(v string) *CarpoolTermUpdateOne {
	_u.mutation.SetSourceMode(v)
	return _u
}

// SetNillableSourceMode sets the "source_mode" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableSourceMode(v *string) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetSourceMode(*v)
	}
	return _u
}

// SetHistoryComplete sets the "history_complete" field.
func (_u *CarpoolTermUpdateOne) SetHistoryComplete(v bool) *CarpoolTermUpdateOne {
	_u.mutation.SetHistoryComplete(v)
	return _u
}

// SetNillableHistoryComplete sets the "history_complete" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableHistoryComplete(v *bool) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetHistoryComplete(*v)
	}
	return _u
}

// SetStatisticsSince sets the "statistics_since" field.
func (_u *CarpoolTermUpdateOne) SetStatisticsSince(v time.Time) *CarpoolTermUpdateOne {
	_u.mutation.SetStatisticsSince(v)
	return _u
}

// SetNillableStatisticsSince sets the "statistics_since" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableStatisticsSince(v *time.Time) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetStatisticsSince(*v)
	}
	return _u
}

// ClearStatisticsSince clears the value of the "statistics_since" field.
func (_u *CarpoolTermUpdateOne) ClearStatisticsSince() *CarpoolTermUpdateOne {
	_u.mutation.ClearStatisticsSince()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *CarpoolTermUpdateOne) SetCreatedBy(v int64) *CarpoolTermUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableCreatedBy(v *int64) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *CarpoolTermUpdateOne) AddCreatedBy(v int64) *CarpoolTermUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CarpoolTermUpdateOne) SetNotes(v string) *CarpoolTermUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableNotes(v *string) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *CarpoolTermUpdateOne) ClearNotes() *CarpoolTermUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetTerminatedAt sets the "terminated_at" field.
func (_u *CarpoolTermUpdateOne) SetTerminatedAt(v time.Time) *CarpoolTermUpdateOne {
	_u.mutation.SetTerminatedAt(v)
	return _u
}

// SetNillableTerminatedAt sets the "terminated_at" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableTerminatedAt(v *time.Time) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetTerminatedAt(*v)
	}
	return _u
}

// ClearTerminatedAt clears the value of the "terminated_at" field.
func (_u *CarpoolTermUpdateOne) ClearTerminatedAt() *CarpoolTermUpdateOne {
	_u.mutation.ClearTerminatedAt()
	return _u
}

// SetTerminatedBy sets the "terminated_by" field.
func (_u *CarpoolTermUpdateOne) SetTerminatedBy(v int64) *CarpoolTermUpdateOne {
	_u.mutation.ResetTerminatedBy()
	_u.mutation.SetTerminatedBy(v)
	return _u
}

// SetNillableTerminatedBy sets the "terminated_by" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableTerminatedBy(v *int64) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetTerminatedBy(*v)
	}
	return _u
}

// AddTerminatedBy adds value to the "terminated_by" field.
func (_u *CarpoolTermUpdateOne) AddTerminatedBy(v int64) *CarpoolTermUpdateOne {
	_u.mutation.AddTerminatedBy(v)
	return _u
}

// ClearTerminatedBy clears the value of the "terminated_by" field.
func (_u *CarpoolTermUpdateOne) ClearTerminatedBy() *CarpoolTermUpdateOne {
	_u.mutation.ClearTerminatedBy()
	return _u
}

// SetTerminationReason sets the "termination_reason" field.
func (_u *CarpoolTermUpdateOne) SetTerminationReason(v string) *CarpoolTermUpdateOne {
	_u.mutation.SetTerminationReason(v)
	return _u
}

// SetNillableTerminationReason sets the "termination_reason" field if the given value is not nil.
func (_u *CarpoolTermUpdateOne) SetNillableTerminationReason(v *string) *CarpoolTermUpdateOne {
	if v != nil {
		_u.SetTerminationReason(*v)
	}
	return _u
}

// ClearTerminationReason clears the value of the "termination_reason" field.
func (_u *CarpoolTermUpdateOne) ClearTerminationReason() *CarpoolTermUpdateOne {
	_u.mutation.ClearTerminationReason()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CarpoolTermUpdateOne) SetUpdatedAt(v time.Time) *CarpoolTermUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CarpoolTermMutation object of the builder.
func (_u *CarpoolTermUpdateOne) Mutation() *CarpoolTermMutation {
	return _u.mutation
}

// Where appends a list predicates to the CarpoolTermUpdate builder.
func (_u *CarpoolTermUpdateOne) Where(ps ...predicate.CarpoolTerm) *CarpoolTermUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CarpoolTermUpdateOne) Select(field string, fields ...string) *CarpoolTermUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CarpoolTerm entity.
func (_u *CarpoolTermUpdateOne) Save(ctx context.Context) (*CarpoolTerm, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CarpoolTermUpdateOne) SaveX(ctx context.Context) *CarpoolTerm {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CarpoolTermUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CarpoolTermUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CarpoolTermUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carpoolterm.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CarpoolTermUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := carpoolterm.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CarpoolTerm.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceMode(); ok {
		if err := carpoolterm.SourceModeValidator(v); err != nil {
			return &ValidationError{Name: "source_mode", err: fmt.Errorf(`ent: validator failed for field "CarpoolTerm.source_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *CarpoolTermUpdateOne) sqlSave(ctx context.Context) (_node *CarpoolTerm, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carpoolterm.Table, carpoolterm.Columns, sqlgraph.NewFieldSpec(carpoolterm.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CarpoolTerm.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carpoolterm.FieldID)
		for _, f := range fields {
			if !carpoolterm.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != carpoolterm.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(carpoolterm.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(carpoolterm.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(carpoolterm.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScopeID(); ok {
		_spec.AddField(carpoolterm.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(carpoolterm.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(carpoolterm.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(carpoolterm.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(carpoolterm.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlanSnapshot(); ok {
		_spec.SetField(carpoolterm.FieldPlanSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(carpoolterm.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(carpoolterm.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(carpoolterm.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BoostUsed(); ok {
		_spec.SetField(carpoolterm.FieldBoostUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBoostUsed(); ok {
		_spec.AddField(carpoolterm.FieldBoostUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceMode(); ok {
		_spec.SetField(carpoolterm.FieldSourceMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.HistoryComplete(); ok {
		_spec.SetField(carpoolterm.FieldHistoryComplete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatisticsSince(); ok {
		_spec.SetField(carpoolterm.FieldStatisticsSince, field.TypeTime, value)
	}
	if _u.mutation.StatisticsSinceCleared() {
		_spec.ClearField(carpoolterm.FieldStatisticsSince, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(carpoolterm.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(carpoolterm.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(carpoolterm.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(carpoolterm.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.TerminatedAt(); ok {
		_spec.SetField(carpoolterm.FieldTerminatedAt, field.TypeTime, value)
	}
	if _u.mutation.TerminatedAtCleared() {
		_spec.ClearField(carpoolterm.FieldTerminatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TerminatedBy(); ok {
		_spec.SetField(carpoolterm.FieldTerminatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTerminatedBy(); ok {
		_spec.AddField(carpoolterm.FieldTerminatedBy, field.TypeInt64, value)
	}
	if _u.mutation.TerminatedByCleared() {
		_spec.ClearField(carpoolterm.FieldTerminatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.TerminationReason(); ok {
		_spec.SetField(carpoolterm.FieldTerminationReason, field.TypeString, value)
	}
	if _u.mutation.TerminationReasonCleared() {
		_spec.ClearField(carpoolterm.FieldTerminationReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolterm.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CarpoolTerm{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carpoolterm.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
