// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/carpoolcycle"
)

// CarpoolCycle is the model entity for the CarpoolCycle schema.
type CarpoolCycle struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TermID holds the value of the "term_id" field.
	TermID int64 `json:"term_id,omitempty"`
	// CycleNo holds the value of the "cycle_no" field.
	CycleNo int `json:"cycle_no,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// EndsAt holds the value of the "ends_at" field.
	EndsAt time.Time `json:"ends_at,omitempty"`
	// BaseQuotaUsd holds the value of the "base_quota_usd" field.
	BaseQuotaUsd float64 `json:"base_quota_usd,omitempty"`
	// BaseBalanceUsd holds the value of the "base_balance_usd" field.
	BaseBalanceUsd float64 `json:"base_balance_usd,omitempty"`
	// BoostBalanceUsd holds the value of the "boost_balance_usd" field.
	BoostBalanceUsd float64 `json:"boost_balance_usd,omitempty"`
	// ManualBalanceUsd holds the value of the "manual_balance_usd" field.
	ManualBalanceUsd float64 `json:"manual_balance_usd,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int64 `json:"revision,omitempty"`
	// ActivatedAt holds the value of the "activated_at" field.
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CarpoolCycle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carpoolcycle.FieldBaseQuotaUsd, carpoolcycle.FieldBaseBalanceUsd, carpoolcycle.FieldBoostBalanceUsd, carpoolcycle.FieldManualBalanceUsd:
			values[i] = new(sql.NullFloat64)
		case carpoolcycle.FieldID, carpoolcycle.FieldTermID, carpoolcycle.FieldCycleNo, carpoolcycle.FieldRevision:
			values[i] = new(sql.NullInt64)
		case carpoolcycle.FieldState:
			values[i] = new(sql.NullString)
		case carpoolcycle.FieldStartsAt, carpoolcycle.FieldEndsAt, carpoolcycle.FieldActivatedAt, carpoolcycle.FieldClosedAt, carpoolcycle.FieldCreatedAt, carpoolcycle.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CarpoolCycle fields.
func (_m *CarpoolCycle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carpoolcycle.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case carpoolcycle.FieldTermID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field term_id", values[i])
			} else if value.Valid {
				_m.TermID = value.Int64
			}
		case carpoolcycle.FieldCycleNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_no", values[i])
			} else if value.Valid {
				_m.CycleNo = int(value.Int64)
			}
		case carpoolcycle.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case carpoolcycle.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = value.Time
			}
		case carpoolcycle.FieldBaseQuotaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_quota_usd", values[i])
			} else if value.Valid {
				_m.BaseQuotaUsd = value.Float64
			}
		case carpoolcycle.FieldBaseBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_balance_usd", values[i])
			} else if value.Valid {
				_m.BaseBalanceUsd = value.Float64
			}
		case carpoolcycle.FieldBoostBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field boost_balance_usd", values[i])
			} else if value.Valid {
				_m.BoostBalanceUsd = value.Float64
			}
		case carpoolcycle.FieldManualBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field manual_balance_usd", values[i])
			} else if value.Valid {
				_m.ManualBalanceUsd = value.Float64
			}
		case carpoolcycle.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case carpoolcycle.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.Int64
			}
		case carpoolcycle.FieldActivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field activated_at", values[i])
			} else if value.Valid {
				_m.ActivatedAt = new(time.Time)
				*_m.ActivatedAt = value.Time
			}
		case carpoolcycle.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case carpoolcycle.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case carpoolcycle.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CarpoolCycle.
// This includes values selected through modifiers, order, etc.
func (_m *CarpoolCycle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CarpoolCycle.
// Note that you need to call CarpoolCycle.Unwrap() before calling this method if this CarpoolCycle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CarpoolCycle) Update() *CarpoolCycleUpdateOne {
	return NewCarpoolCycleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CarpoolCycle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CarpoolCycle) Unwrap() *CarpoolCycle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CarpoolCycle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CarpoolCycle) String() string {
	var builder strings.Builder
	builder.WriteString("CarpoolCycle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("term_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TermID))
	builder.WriteString(", ")
	builder.WriteString("cycle_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.CycleNo))
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ends_at=")
	builder.WriteString(_m.EndsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("base_quota_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseQuotaUsd))
	builder.WriteString(", ")
	builder.WriteString("base_balance_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseBalanceUsd))
	builder.WriteString(", ")
	builder.WriteString("boost_balance_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.BoostBalanceUsd))
	builder.WriteString(", ")
	builder.WriteString("manual_balance_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManualBalanceUsd))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	if v := _m.ActivatedAt; v != nil {
		builder.WriteString("activated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CarpoolCycles is a parsable slice of CarpoolCycle.
type CarpoolCycles []*CarpoolCycle
