// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpooloperation"
)

// CarpoolOperationCreate is the builder for creating a CarpoolOperation entity.
type CarpoolOperationCreate struct {
	config
	mutation *CarpoolOperationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKind sets the "kind" field.
func (_c *CarpoolOperationCreate) SetKind(v string) *CarpoolOperationCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *CarpoolOperationCreate) SetActorID(v int64) *CarpoolOperationCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *CarpoolOperationCreate) SetKeyHash(v string) *CarpoolOperationCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_c *CarpoolOperationCreate) SetRequestFingerprint(v string) *CarpoolOperationCreate {
	_c.mutation.SetRequestFingerprint(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *CarpoolOperationCreate) SetResourceType(v string) *CarpoolOperationCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *CarpoolOperationCreate) SetResourceID(v int64) *CarpoolOperationCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetResponse sets the "response" field.
func (_c *CarpoolOperationCreate) SetResponse(v map[string]interface{}) *CarpoolOperationCreate {
	_c.mutation.SetResponse(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CarpoolOperationCreate) SetCreatedAt(v time.Time) *CarpoolOperationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CarpoolOperationCreate) SetNillableCreatedAt(v *time.Time) *CarpoolOperationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CarpoolOperationMutation object of the builder.
func (_c *CarpoolOperationCreate) Mutation() *CarpoolOperationMutation {
	return _c.mutation
}

// Save creates the CarpoolOperation in the database.
func (_c *CarpoolOperationCreate) Save(ctx context.Context) (*CarpoolOperation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarpoolOperationCreate) SaveX(ctx context.Context) *CarpoolOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolOperationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolOperationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarpoolOperationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := carpooloperation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarpoolOperationCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "CarpoolOperation.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := carpooloperation.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "CarpoolOperation.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "CarpoolOperation.actor_id"`)}
	}
	if _, ok := _c.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "CarpoolOperation.key_hash"`)}
	}
	if v, ok := _c.mutation.KeyHash(); ok {
		if err := carpooloperation.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "CarpoolOperation.key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestFingerprint(); !ok {
		return &ValidationError{Name: "request_fingerprint", err: errors.New(`ent: missing required field "CarpoolOperation.request_fingerprint"`)}
	}
	if v, ok := _c.mutation.RequestFingerprint(); ok {
		if err := carpooloperation.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "CarpoolOperation.request_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "CarpoolOperation.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := carpooloperation.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "CarpoolOperation.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "CarpoolOperation.resource_id"`)}
	}
	if _, ok := _c.mutation.Response(); !ok {
		return &ValidationError{Name: "response", err: errors.New(`ent: missing required field "CarpoolOperation.response"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CarpoolOperation.created_at"`)}
	}
	return nil
}

func (_c *CarpoolOperationCreate) sqlSave(ctx context.Context) (*CarpoolOperation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarpoolOperationCreate) createSpec() (*CarpoolOperation, *sqlgraph.CreateSpec) {
	var (
		_node = &CarpoolOperation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carpooloperation.Table, sqlgraph.NewFieldSpec(carpooloperation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(carpooloperation.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(carpooloperation.FieldActorID, field.TypeInt64, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(carpooloperation.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = value
	}
	if value, ok := _c.mutation.RequestFingerprint(); ok {
		_spec.SetField(carpooloperation.FieldRequestFingerprint, field.TypeString, value)
		_node.RequestFingerprint = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(carpooloperation.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(carpooloperation.FieldResourceID, field.TypeInt64, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Response(); ok {
		_spec.SetField(carpooloperation.FieldResponse, field.TypeJSON, value)
		_node.Response = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carpooloperation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolOperation.Create().
//		SetKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolOperationUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolOperationCreate) OnConflict(opts ...sql.ConflictOption) *CarpoolOperationUpsertOne {
	_c.conflict = opts
	return &CarpoolOperationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolOperation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolOperationCreate) OnConflictColumns(columns ...string) *CarpoolOperationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolOperationUpsertOne{
		create: _c,
	}
}

type (
	// CarpoolOperationUpsertOne is the builder for "upsert"-ing
	//  one CarpoolOperation node.
	CarpoolOperationUpsertOne struct {
		create *CarpoolOperationCreate
	}

	// CarpoolOperationUpsert is the "OnConflict" setter.
	CarpoolOperationUpsert struct {
		*sql.UpdateSet
	}
)

// SetKind sets the "kind" field.
func (u *CarpoolOperationUpsert) SetKind(v string) *CarpoolOperationUpsert {
	u.Set(carpooloperation.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *CarpoolOperationUpsert) UpdateKind() *CarpoolOperationUpsert {
	u.SetExcluded(carpooloperation.FieldKind)
	return u
}

// SetActorID sets the "actor_id" field.
func (u *CarpoolOperationUpsert) SetActorID(v int64) *CarpoolOperationUpsert {
	u.Set(carpooloperation.FieldActorID, v)
	return u
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *CarpoolOperationUpsert) UpdateActorID() *CarpoolOperationUpsert {
	u.SetExcluded(carpooloperation.FieldActorID)
	return u
}

// AddActorID adds v to the "actor_id" field.
func (u *CarpoolOperationUpsert) AddActorID(v int64) *CarpoolOperationUpsert {
	u.Add(carpooloperation.FieldActorID, v)
	return u
}

// SetKeyHash sets the "key_hash" field.
func (u *CarpoolOperationUpsert) SetKeyHash(v string) *CarpoolOperationUpsert {
	u.Set(carpooloperation.FieldKeyHash, v)
	return u
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *CarpoolOperationUpsert) UpdateKeyHash() *CarpoolOperationUpsert {
	u.SetExcluded(carpooloperation.FieldKeyHash)
	return u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *CarpoolOperationUpsert) SetRequestFingerprint(v string) *CarpoolOperationUpsert {
	u.Set(carpooloperation.FieldRequestFingerprint, v)
	return u
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *CarpoolOperationUpsert) UpdateRequestFingerprint() *CarpoolOperationUpsert {
	u.SetExcluded(carpooloperation.FieldRequestFingerprint)
	return u
}

// SetResourceType sets the "resource_type" field.
func (u *CarpoolOperationUpsert) SetResourceType(v string) *CarpoolOperationUpsert {
	u.Set(carpooloperation.FieldResourceType, v)
	return u
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *CarpoolOperationUpsert) UpdateResourceType() *CarpoolOperationUpsert {
	u.SetExcluded(carpooloperation.FieldResourceType)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *CarpoolOperationUpsert) SetResourceID(v int64) *CarpoolOperationUpsert {
	u.Set(carpooloperation.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *CarpoolOperationUpsert) UpdateResourceID() *CarpoolOperationUpsert {
	u.SetExcluded(carpooloperation.FieldResourceID)
	return u
}

// AddResourceID adds v to the "resource_id" field.
func (u *CarpoolOperationUpsert) AddResourceID(v int64) *CarpoolOperationUpsert {
	u.Add(carpooloperation.FieldResourceID, v)
	return u
}

// SetResponse sets the "response" field.
func (u *CarpoolOperationUpsert) SetResponse(v map[string]interface{}) *CarpoolOperationUpsert {
	u.Set(carpooloperation.FieldResponse, v)
	return u
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *CarpoolOperationUpsert) UpdateResponse() *CarpoolOperationUpsert {
	u.SetExcluded(carpooloperation.FieldResponse)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CarpoolOperation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolOperationUpsertOne) UpdateNewValues() *CarpoolOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(carpooloperation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolOperation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarpoolOperationUpsertOne) Ignore() *CarpoolOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolOperationUpsertOne) DoNothing() *CarpoolOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolOperationCreate.OnConflict
// documentation for more info.
func (u *CarpoolOperationUpsertOne) Update(set func(*CarpoolOperationUpsert)) *CarpoolOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolOperationUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *CarpoolOperationUpsertOne) SetKind(v string) *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *CarpoolOperationUpsertOne) UpdateKind() *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateKind()
	})
}

// SetActorID sets the "actor_id" field.
func (u *CarpoolOperationUpsertOne) SetActorID(v int64) *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetActorID(v)
	})
}

// AddActorID adds v to the "actor_id" field.
func (u *CarpoolOperationUpsertOne) AddActorID(v int64) *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.AddActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *CarpoolOperationUpsertOne) UpdateActorID() *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateActorID()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *CarpoolOperationUpsertOne) SetKeyHash(v string) *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *CarpoolOperationUpsertOne) UpdateKeyHash() *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateKeyHash()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *CarpoolOperationUpsertOne) SetRequestFingerprint(v string) *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *CarpoolOperationUpsertOne) UpdateRequestFingerprint() *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *CarpoolOperationUpsertOne) SetResourceType(v string) *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *CarpoolOperationUpsertOne) UpdateResourceType() *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *CarpoolOperationUpsertOne) SetResourceID(v int64) *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *CarpoolOperationUpsertOne) AddResourceID(v int64) *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *CarpoolOperationUpsertOne) UpdateResourceID() *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateResourceID()
	})
}

// SetResponse sets the "response" field.
func (u *CarpoolOperationUpsertOne) SetResponse(v map[string]interface{}) *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetResponse(v)
	})
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *CarpoolOperationUpsertOne) UpdateResponse() *CarpoolOperationUpsertOne {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateResponse()
	})
}

// Exec executes the query.
func (u *CarpoolOperationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolOperationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolOperationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarpoolOperationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarpoolOperationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarpoolOperationCreateBulk is the builder for creating many CarpoolOperation entities in bulk.
type CarpoolOperationCreateBulk struct {
	config
	err      error
	builders []*CarpoolOperationCreate
	conflict []sql.ConflictOption
}

// Save creates the CarpoolOperation entities in the database.
func (_c *CarpoolOperationCreateBulk) Save(ctx context.Context) ([]*CarpoolOperation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarpoolOperation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarpoolOperationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarpoolOperationCreateBulk) SaveX(ctx context.Context) []*CarpoolOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolOperationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolOperationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolOperation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolOperationUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolOperationCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarpoolOperationUpsertBulk {
	_c.conflict = opts
	return &CarpoolOperationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolOperation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolOperationCreateBulk) OnConflictColumns(columns ...string) *CarpoolOperationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolOperationUpsertBulk{
		create: _c,
	}
}

// CarpoolOperationUpsertBulk is the builder for "upsert"-ing
// a bulk of CarpoolOperation nodes.
type CarpoolOperationUpsertBulk struct {
	create *CarpoolOperationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarpoolOperation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolOperationUpsertBulk) UpdateNewValues() *CarpoolOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(carpooloperation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolOperation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarpoolOperationUpsertBulk) Ignore() *CarpoolOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolOperationUpsertBulk) DoNothing() *CarpoolOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolOperationCreateBulk.OnConflict
// documentation for more info.
func (u *CarpoolOperationUpsertBulk) Update(set func(*CarpoolOperationUpsert)) *CarpoolOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolOperationUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *CarpoolOperationUpsertBulk) SetKind(v string) *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *CarpoolOperationUpsertBulk) UpdateKind() *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateKind()
	})
}

// SetActorID sets the "actor_id" field.
func (u *CarpoolOperationUpsertBulk) SetActorID(v int64) *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetActorID(v)
	})
}

// AddActorID adds v to the "actor_id" field.
func (u *CarpoolOperationUpsertBulk) AddActorID(v int64) *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.AddActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *CarpoolOperationUpsertBulk) UpdateActorID() *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateActorID()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *CarpoolOperationUpsertBulk) SetKeyHash(v string) *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *CarpoolOperationUpsertBulk) UpdateKeyHash() *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateKeyHash()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *CarpoolOperationUpsertBulk) SetRequestFingerprint(v string) *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *CarpoolOperationUpsertBulk) UpdateRequestFingerprint() *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *CarpoolOperationUpsertBulk) SetResourceType(v string) *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *CarpoolOperationUpsertBulk) UpdateResourceType() *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *CarpoolOperationUpsertBulk) SetResourceID(v int64) *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *CarpoolOperationUpsertBulk) AddResourceID(v int64) *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *CarpoolOperationUpsertBulk) UpdateResourceID() *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateResourceID()
	})
}

// SetResponse sets the "response" field.
func (u *CarpoolOperationUpsertBulk) SetResponse(v map[string]interface{}) *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.SetResponse(v)
	})
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *CarpoolOperationUpsertBulk) UpdateResponse() *CarpoolOperationUpsertBulk {
	return u.Update(func(s *CarpoolOperationUpsert) {
		s.UpdateResponse()
	})
}

// Exec executes the query.
func (u *CarpoolOperationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarpoolOperationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolOperationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolOperationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
