// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/carpoolpayment"
)

// CarpoolPayment is the model entity for the CarpoolPayment schema.
type CarpoolPayment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TermID holds the value of the "term_id" field.
	TermID int64 `json:"term_id,omitempty"`
	// AmountCny holds the value of the "amount_cny" field.
	AmountCny float64 `json:"amount_cny,omitempty"`
	// PaymentKind holds the value of the "payment_kind" field.
	PaymentKind string `json:"payment_kind,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt time.Time `json:"paid_at,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel string `json:"channel,omitempty"`
	// ExternalOrderNo holds the value of the "external_order_no" field.
	ExternalOrderNo *string `json:"external_order_no,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint string `json:"request_fingerprint,omitempty"`
	// RecordedBy holds the value of the "recorded_by" field.
	RecordedBy int64 `json:"recorded_by,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// RecordedAt holds the value of the "recorded_at" field.
	RecordedAt   time.Time `json:"recorded_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CarpoolPayment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carpoolpayment.FieldAmountCny:
			values[i] = new(sql.NullFloat64)
		case carpoolpayment.FieldID, carpoolpayment.FieldTermID, carpoolpayment.FieldRecordedBy:
			values[i] = new(sql.NullInt64)
		case carpoolpayment.FieldPaymentKind, carpoolpayment.FieldChannel, carpoolpayment.FieldExternalOrderNo, carpoolpayment.FieldRequestID, carpoolpayment.FieldRequestFingerprint, carpoolpayment.FieldNotes:
			values[i] = new(sql.NullString)
		case carpoolpayment.FieldPaidAt, carpoolpayment.FieldRecordedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CarpoolPayment fields.
func (_m *CarpoolPayment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carpoolpayment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case carpoolpayment.FieldTermID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field term_id", values[i])
			} else if value.Valid {
				_m.TermID = value.Int64
			}
		case carpoolpayment.FieldAmountCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cny", values[i])
			} else if value.Valid {
				_m.AmountCny = value.Float64
			}
		case carpoolpayment.FieldPaymentKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_kind", values[i])
			} else if value.Valid {
				_m.PaymentKind = value.String
			}
		case carpoolpayment.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = value.Time
			}
		case carpoolpayment.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = value.String
			}
		case carpoolpayment.FieldExternalOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_order_no", values[i])
			} else if value.Valid {
				_m.ExternalOrderNo = new(string)
				*_m.ExternalOrderNo = value.String
			}
		case carpoolpayment.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case carpoolpayment.FieldRequestFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value.Valid {
				_m.RequestFingerprint = value.String
			}
		case carpoolpayment.FieldRecordedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recorded_by", values[i])
			} else if value.Valid {
				_m.RecordedBy = value.Int64
			}
		case carpoolpayment.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case carpoolpayment.FieldRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recorded_at", values[i])
			} else if value.Valid {
				_m.RecordedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CarpoolPayment.
// This includes values selected through modifiers, order, etc.
func (_m *CarpoolPayment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CarpoolPayment.
// Note that you need to call CarpoolPayment.Unwrap() before calling this method if this CarpoolPayment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CarpoolPayment) Update() *CarpoolPaymentUpdateOne {
	return NewCarpoolPaymentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CarpoolPayment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CarpoolPayment) Unwrap() *CarpoolPayment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CarpoolPayment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CarpoolPayment) String() string {
	var builder strings.Builder
	builder.WriteString("CarpoolPayment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("term_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TermID))
	builder.WriteString(", ")
	builder.WriteString("amount_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCny))
	builder.WriteString(", ")
	builder.WriteString("payment_kind=")
	builder.WriteString(_m.PaymentKind)
	builder.WriteString(", ")
	builder.WriteString("paid_at=")
	builder.WriteString(_m.PaidAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(_m.Channel)
	builder.WriteString(", ")
	if v := _m.ExternalOrderNo; v != nil {
		builder.WriteString("external_order_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("request_fingerprint=")
	builder.WriteString(_m.RequestFingerprint)
	builder.WriteString(", ")
	builder.WriteString("recorded_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecordedBy))
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("recorded_at=")
	builder.WriteString(_m.RecordedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CarpoolPayments is a parsable slice of CarpoolPayment.
type CarpoolPayments []*CarpoolPayment
