// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/carpoolresetannouncementoutbox"
)

// CarpoolResetAnnouncementOutbox is the model entity for the CarpoolResetAnnouncementOutbox schema.
type CarpoolResetAnnouncementOutbox struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// BatchID holds the value of the "batch_id" field.
	BatchID int64 `json:"batch_id,omitempty"`
	// ScopeID holds the value of the "scope_id" field.
	ScopeID int64 `json:"scope_id,omitempty"`
	// EventKind holds the value of the "event_kind" field.
	EventKind string `json:"event_kind,omitempty"`
	// ScheduleRevision holds the value of the "schedule_revision" field.
	ScheduleRevision int `json:"schedule_revision,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AnnouncementID holds the value of the "announcement_id" field.
	AnnouncementID *int64 `json:"announcement_id,omitempty"`
	// OriginalAnnouncementID holds the value of the "original_announcement_id" field.
	OriginalAnnouncementID *int64 `json:"original_announcement_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt time.Time `json:"next_attempt_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CarpoolResetAnnouncementOutbox) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carpoolresetannouncementoutbox.FieldID, carpoolresetannouncementoutbox.FieldBatchID, carpoolresetannouncementoutbox.FieldScopeID, carpoolresetannouncementoutbox.FieldScheduleRevision, carpoolresetannouncementoutbox.FieldAnnouncementID, carpoolresetannouncementoutbox.FieldOriginalAnnouncementID, carpoolresetannouncementoutbox.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case carpoolresetannouncementoutbox.FieldEventKind, carpoolresetannouncementoutbox.FieldStatus, carpoolresetannouncementoutbox.FieldTitle, carpoolresetannouncementoutbox.FieldContent, carpoolresetannouncementoutbox.FieldLastError:
			values[i] = new(sql.NullString)
		case carpoolresetannouncementoutbox.FieldNextAttemptAt, carpoolresetannouncementoutbox.FieldPublishedAt, carpoolresetannouncementoutbox.FieldCreatedAt, carpoolresetannouncementoutbox.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CarpoolResetAnnouncementOutbox fields.
func (_m *CarpoolResetAnnouncementOutbox) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carpoolresetannouncementoutbox.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case carpoolresetannouncementoutbox.FieldBatchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field batch_id", values[i])
			} else if value.Valid {
				_m.BatchID = value.Int64
			}
		case carpoolresetannouncementoutbox.FieldScopeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field scope_id", values[i])
			} else if value.Valid {
				_m.ScopeID = value.Int64
			}
		case carpoolresetannouncementoutbox.FieldEventKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_kind", values[i])
			} else if value.Valid {
				_m.EventKind = value.String
			}
		case carpoolresetannouncementoutbox.FieldScheduleRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field schedule_revision", values[i])
			} else if value.Valid {
				_m.ScheduleRevision = int(value.Int64)
			}
		case carpoolresetannouncementoutbox.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case carpoolresetannouncementoutbox.FieldAnnouncementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field announcement_id", values[i])
			} else if value.Valid {
				_m.AnnouncementID = new(int64)
				*_m.AnnouncementID = value.Int64
			}
		case carpoolresetannouncementoutbox.FieldOriginalAnnouncementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field original_announcement_id", values[i])
			} else if value.Valid {
				_m.OriginalAnnouncementID = new(int64)
				*_m.OriginalAnnouncementID = value.Int64
			}
		case carpoolresetannouncementoutbox.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case carpoolresetannouncementoutbox.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case carpoolresetannouncementoutbox.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case carpoolresetannouncementoutbox.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = value.Time
			}
		case carpoolresetannouncementoutbox.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case carpoolresetannouncementoutbox.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case carpoolresetannouncementoutbox.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case carpoolresetannouncementoutbox.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CarpoolResetAnnouncementOutbox.
// This includes values selected through modifiers, order, etc.
func (_m *CarpoolResetAnnouncementOutbox) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CarpoolResetAnnouncementOutbox.
// Note that you need to call CarpoolResetAnnouncementOutbox.Unwrap() before calling this method if this CarpoolResetAnnouncementOutbox
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CarpoolResetAnnouncementOutbox) Update() *CarpoolResetAnnouncementOutboxUpdateOne {
	return NewCarpoolResetAnnouncementOutboxClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CarpoolResetAnnouncementOutbox entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CarpoolResetAnnouncementOutbox) Unwrap() *CarpoolResetAnnouncementOutbox {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CarpoolResetAnnouncementOutbox is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CarpoolResetAnnouncementOutbox) String() string {
	var builder strings.Builder
	builder.WriteString("CarpoolResetAnnouncementOutbox(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("batch_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchID))
	builder.WriteString(", ")
	builder.WriteString("scope_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScopeID))
	builder.WriteString(", ")
	builder.WriteString("event_kind=")
	builder.WriteString(_m.EventKind)
	builder.WriteString(", ")
	builder.WriteString("schedule_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScheduleRevision))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.AnnouncementID; v != nil {
		builder.WriteString("announcement_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OriginalAnnouncementID; v != nil {
		builder.WriteString("original_announcement_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("next_attempt_at=")
	builder.WriteString(_m.NextAttemptAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CarpoolResetAnnouncementOutboxes is a parsable slice of CarpoolResetAnnouncementOutbox.
type CarpoolResetAnnouncementOutboxes []*CarpoolResetAnnouncementOutbox
