// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolresetannouncementoutbox"
)

// CarpoolResetAnnouncementOutboxCreate is the builder for creating a CarpoolResetAnnouncementOutbox entity.
type CarpoolResetAnnouncementOutboxCreate struct {
	config
	mutation *CarpoolResetAnnouncementOutboxMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBatchID sets the "batch_id" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetBatchID(v int64) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetScopeID(v int64) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetEventKind sets the "event_kind" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetEventKind(v string) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetEventKind(v)
	return _c
}

// SetScheduleRevision sets the "schedule_revision" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetScheduleRevision(v int) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetScheduleRevision(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetStatus(v string) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNillableStatus(v *string) *CarpoolResetAnnouncementOutboxCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAnnouncementID sets the "announcement_id" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetAnnouncementID(v)
	return _c
}

// SetNillableAnnouncementID sets the "announcement_id" field if the given value is not nil.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNillableAnnouncementID(v *int64) *CarpoolResetAnnouncementOutboxCreate {
	if v != nil {
		_c.SetAnnouncementID(*v)
	}
	return _c
}

// SetOriginalAnnouncementID sets the "original_announcement_id" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetOriginalAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetOriginalAnnouncementID(v)
	return _c
}

// SetNillableOriginalAnnouncementID sets the "original_announcement_id" field if the given value is not nil.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNillableOriginalAnnouncementID(v *int64) *CarpoolResetAnnouncementOutboxCreate {
	if v != nil {
		_c.SetOriginalAnnouncementID(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetTitle(v string) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetContent(v string) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetAttempts(v int) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNillableAttempts(v *int) *CarpoolResetAnnouncementOutboxCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNextAttemptAt(v time.Time) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNillableNextAttemptAt(v *time.Time) *CarpoolResetAnnouncementOutboxCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetLastError(v string) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNillableLastError(v *string) *CarpoolResetAnnouncementOutboxCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetPublishedAt(v time.Time) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNillablePublishedAt(v *time.Time) *CarpoolResetAnnouncementOutboxCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetCreatedAt(v time.Time) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNillableCreatedAt(v *time.Time) *CarpoolResetAnnouncementOutboxCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetUpdatedAt(v time.Time) *CarpoolResetAnnouncementOutboxCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CarpoolResetAnnouncementOutboxCreate) SetNillableUpdatedAt(v *time.Time) *CarpoolResetAnnouncementOutboxCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CarpoolResetAnnouncementOutboxMutation object of the builder.
func (_c *CarpoolResetAnnouncementOutboxCreate) Mutation() *CarpoolResetAnnouncementOutboxMutation {
	return _c.mutation
}

// Save creates the CarpoolResetAnnouncementOutbox in the database.
func (_c *CarpoolResetAnnouncementOutboxCreate) Save(ctx context.Context) (*CarpoolResetAnnouncementOutbox, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarpoolResetAnnouncementOutboxCreate) SaveX(ctx context.Context) *CarpoolResetAnnouncementOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolResetAnnouncementOutboxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolResetAnnouncementOutboxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarpoolResetAnnouncementOutboxCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := carpoolresetannouncementoutbox.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := carpoolresetannouncementoutbox.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.NextAttemptAt(); !ok {
		v := carpoolresetannouncementoutbox.DefaultNextAttemptAt()
		_c.mutation.SetNextAttemptAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := carpoolresetannouncementoutbox.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := carpoolresetannouncementoutbox.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarpoolResetAnnouncementOutboxCreate) check() error {
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.batch_id"`)}
	}
	if _, ok := _c.mutation.ScopeID(); !ok {
		return &ValidationError{Name: "scope_id", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.scope_id"`)}
	}
	if _, ok := _c.mutation.EventKind(); !ok {
		return &ValidationError{Name: "event_kind", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.event_kind"`)}
	}
	if v, ok := _c.mutation.EventKind(); ok {
		if err := carpoolresetannouncementoutbox.EventKindValidator(v); err != nil {
			return &ValidationError{Name: "event_kind", err: fmt.Errorf(`ent: validator failed for field "CarpoolResetAnnouncementOutbox.event_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScheduleRevision(); !ok {
		return &ValidationError{Name: "schedule_revision", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.schedule_revision"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := carpoolresetannouncementoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CarpoolResetAnnouncementOutbox.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := carpoolresetannouncementoutbox.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CarpoolResetAnnouncementOutbox.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.content"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.attempts"`)}
	}
	if _, ok := _c.mutation.NextAttemptAt(); !ok {
		return &ValidationError{Name: "next_attempt_at", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.next_attempt_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CarpoolResetAnnouncementOutbox.updated_at"`)}
	}
	return nil
}

func (_c *CarpoolResetAnnouncementOutboxCreate) sqlSave(ctx context.Context) (*CarpoolResetAnnouncementOutbox, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarpoolResetAnnouncementOutboxCreate) createSpec() (*CarpoolResetAnnouncementOutbox, *sqlgraph.CreateSpec) {
	var (
		_node = &CarpoolResetAnnouncementOutbox{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carpoolresetannouncementoutbox.Table, sqlgraph.NewFieldSpec(carpoolresetannouncementoutbox.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BatchID(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldBatchID, field.TypeInt64, value)
		_node.BatchID = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldScopeID, field.TypeInt64, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.EventKind(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldEventKind, field.TypeString, value)
		_node.EventKind = value
	}
	if value, ok := _c.mutation.ScheduleRevision(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldScheduleRevision, field.TypeInt, value)
		_node.ScheduleRevision = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AnnouncementID(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldAnnouncementID, field.TypeInt64, value)
		_node.AnnouncementID = &value
	}
	if value, ok := _c.mutation.OriginalAnnouncementID(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldOriginalAnnouncementID, field.TypeInt64, value)
		_node.OriginalAnnouncementID = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolresetannouncementoutbox.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolResetAnnouncementOutbox.Create().
//		SetBatchID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolResetAnnouncementOutboxUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolResetAnnouncementOutboxCreate) OnConflict(opts ...sql.ConflictOption) *CarpoolResetAnnouncementOutboxUpsertOne {
	_c.conflict = opts
	return &CarpoolResetAnnouncementOutboxUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolResetAnnouncementOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolResetAnnouncementOutboxCreate) OnConflictColumns(columns ...string) *CarpoolResetAnnouncementOutboxUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolResetAnnouncementOutboxUpsertOne{
		create: _c,
	}
}

type (
	// CarpoolResetAnnouncementOutboxUpsertOne is the builder for "upsert"-ing
	//  one CarpoolResetAnnouncementOutbox node.
	CarpoolResetAnnouncementOutboxUpsertOne struct {
		create *CarpoolResetAnnouncementOutboxCreate
	}

	// CarpoolResetAnnouncementOutboxUpsert is the "OnConflict" setter.
	CarpoolResetAnnouncementOutboxUpsert struct {
		*sql.UpdateSet
	}
)

// SetBatchID sets the "batch_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetBatchID(v int64) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateBatchID() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldBatchID)
	return u
}

// AddBatchID adds v to the "batch_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) AddBatchID(v int64) *CarpoolResetAnnouncementOutboxUpsert {
	u.Add(carpoolresetannouncementoutbox.FieldBatchID, v)
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetScopeID(v int64) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateScopeID() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldScopeID)
	return u
}

// AddScopeID adds v to the "scope_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) AddScopeID(v int64) *CarpoolResetAnnouncementOutboxUpsert {
	u.Add(carpoolresetannouncementoutbox.FieldScopeID, v)
	return u
}

// SetEventKind sets the "event_kind" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetEventKind(v string) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldEventKind, v)
	return u
}

// UpdateEventKind sets the "event_kind" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateEventKind() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldEventKind)
	return u
}

// SetScheduleRevision sets the "schedule_revision" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetScheduleRevision(v int) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldScheduleRevision, v)
	return u
}

// UpdateScheduleRevision sets the "schedule_revision" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateScheduleRevision() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldScheduleRevision)
	return u
}

// AddScheduleRevision adds v to the "schedule_revision" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) AddScheduleRevision(v int) *CarpoolResetAnnouncementOutboxUpsert {
	u.Add(carpoolresetannouncementoutbox.FieldScheduleRevision, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetStatus(v string) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateStatus() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldStatus)
	return u
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldAnnouncementID, v)
	return u
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateAnnouncementID() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldAnnouncementID)
	return u
}

// AddAnnouncementID adds v to the "announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) AddAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsert {
	u.Add(carpoolresetannouncementoutbox.FieldAnnouncementID, v)
	return u
}

// ClearAnnouncementID clears the value of the "announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) ClearAnnouncementID() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetNull(carpoolresetannouncementoutbox.FieldAnnouncementID)
	return u
}

// SetOriginalAnnouncementID sets the "original_announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetOriginalAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldOriginalAnnouncementID, v)
	return u
}

// UpdateOriginalAnnouncementID sets the "original_announcement_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateOriginalAnnouncementID() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldOriginalAnnouncementID)
	return u
}

// AddOriginalAnnouncementID adds v to the "original_announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) AddOriginalAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsert {
	u.Add(carpoolresetannouncementoutbox.FieldOriginalAnnouncementID, v)
	return u
}

// ClearOriginalAnnouncementID clears the value of the "original_announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) ClearOriginalAnnouncementID() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetNull(carpoolresetannouncementoutbox.FieldOriginalAnnouncementID)
	return u
}

// SetTitle sets the "title" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetTitle(v string) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateTitle() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetContent(v string) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateContent() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldContent)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetAttempts(v int) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateAttempts() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) AddAttempts(v int) *CarpoolResetAnnouncementOutboxUpsert {
	u.Add(carpoolresetannouncementoutbox.FieldAttempts, v)
	return u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetNextAttemptAt(v time.Time) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldNextAttemptAt, v)
	return u
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateNextAttemptAt() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldNextAttemptAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetLastError(v string) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateLastError() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) ClearLastError() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetNull(carpoolresetannouncementoutbox.FieldLastError)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetPublishedAt(v time.Time) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdatePublishedAt() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) ClearPublishedAt() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetNull(carpoolresetannouncementoutbox.FieldPublishedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsert) SetUpdatedAt(v time.Time) *CarpoolResetAnnouncementOutboxUpsert {
	u.Set(carpoolresetannouncementoutbox.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsert) UpdateUpdatedAt() *CarpoolResetAnnouncementOutboxUpsert {
	u.SetExcluded(carpoolresetannouncementoutbox.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CarpoolResetAnnouncementOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateNewValues() *CarpoolResetAnnouncementOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(carpoolresetannouncementoutbox.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolResetAnnouncementOutbox.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarpoolResetAnnouncementOutboxUpsertOne) Ignore() *CarpoolResetAnnouncementOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) DoNothing() *CarpoolResetAnnouncementOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolResetAnnouncementOutboxCreate.OnConflict
// documentation for more info.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) Update(set func(*CarpoolResetAnnouncementOutboxUpsert)) *CarpoolResetAnnouncementOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolResetAnnouncementOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetBatchID(v int64) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetBatchID(v)
	})
}

// AddBatchID adds v to the "batch_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) AddBatchID(v int64) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateBatchID() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateBatchID()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetScopeID(v int64) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetScopeID(v)
	})
}

// AddScopeID adds v to the "scope_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) AddScopeID(v int64) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateScopeID() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateScopeID()
	})
}

// SetEventKind sets the "event_kind" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetEventKind(v string) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetEventKind(v)
	})
}

// UpdateEventKind sets the "event_kind" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateEventKind() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateEventKind()
	})
}

// SetScheduleRevision sets the "schedule_revision" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetScheduleRevision(v int) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetScheduleRevision(v)
	})
}

// AddScheduleRevision adds v to the "schedule_revision" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) AddScheduleRevision(v int) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddScheduleRevision(v)
	})
}

// UpdateScheduleRevision sets the "schedule_revision" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateScheduleRevision() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateScheduleRevision()
	})
}

// SetStatus sets the "status" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetStatus(v string) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateStatus() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateStatus()
	})
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetAnnouncementID(v)
	})
}

// AddAnnouncementID adds v to the "announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) AddAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateAnnouncementID() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateAnnouncementID()
	})
}

// ClearAnnouncementID clears the value of the "announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) ClearAnnouncementID() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.ClearAnnouncementID()
	})
}

// SetOriginalAnnouncementID sets the "original_announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetOriginalAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetOriginalAnnouncementID(v)
	})
}

// AddOriginalAnnouncementID adds v to the "original_announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) AddOriginalAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddOriginalAnnouncementID(v)
	})
}

// UpdateOriginalAnnouncementID sets the "original_announcement_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateOriginalAnnouncementID() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateOriginalAnnouncementID()
	})
}

// ClearOriginalAnnouncementID clears the value of the "original_announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) ClearOriginalAnnouncementID() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.ClearOriginalAnnouncementID()
	})
}

// SetTitle sets the "title" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetTitle(v string) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateTitle() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetContent(v string) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateContent() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateContent()
	})
}

// SetAttempts sets the "attempts" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetAttempts(v int) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) AddAttempts(v int) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateAttempts() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateAttempts()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetNextAttemptAt(v time.Time) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateNextAttemptAt() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetLastError(v string) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateLastError() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) ClearLastError() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.ClearLastError()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetPublishedAt(v time.Time) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdatePublishedAt() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) ClearPublishedAt() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.ClearPublishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) SetUpdatedAt(v time.Time) *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) UpdateUpdatedAt() *CarpoolResetAnnouncementOutboxUpsertOne {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolResetAnnouncementOutboxCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarpoolResetAnnouncementOutboxUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarpoolResetAnnouncementOutboxCreateBulk is the builder for creating many CarpoolResetAnnouncementOutbox entities in bulk.
type CarpoolResetAnnouncementOutboxCreateBulk struct {
	config
	err      error
	builders []*CarpoolResetAnnouncementOutboxCreate
	conflict []sql.ConflictOption
}

// Save creates the CarpoolResetAnnouncementOutbox entities in the database.
func (_c *CarpoolResetAnnouncementOutboxCreateBulk) Save(ctx context.Context) ([]*CarpoolResetAnnouncementOutbox, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarpoolResetAnnouncementOutbox, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarpoolResetAnnouncementOutboxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarpoolResetAnnouncementOutboxCreateBulk) SaveX(ctx context.Context) []*CarpoolResetAnnouncementOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolResetAnnouncementOutboxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolResetAnnouncementOutboxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolResetAnnouncementOutbox.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolResetAnnouncementOutboxUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolResetAnnouncementOutboxCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarpoolResetAnnouncementOutboxUpsertBulk {
	_c.conflict = opts
	return &CarpoolResetAnnouncementOutboxUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolResetAnnouncementOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolResetAnnouncementOutboxCreateBulk) OnConflictColumns(columns ...string) *CarpoolResetAnnouncementOutboxUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolResetAnnouncementOutboxUpsertBulk{
		create: _c,
	}
}

// CarpoolResetAnnouncementOutboxUpsertBulk is the builder for "upsert"-ing
// a bulk of CarpoolResetAnnouncementOutbox nodes.
type CarpoolResetAnnouncementOutboxUpsertBulk struct {
	create *CarpoolResetAnnouncementOutboxCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarpoolResetAnnouncementOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateNewValues() *CarpoolResetAnnouncementOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(carpoolresetannouncementoutbox.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolResetAnnouncementOutbox.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) Ignore() *CarpoolResetAnnouncementOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) DoNothing() *CarpoolResetAnnouncementOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolResetAnnouncementOutboxCreateBulk.OnConflict
// documentation for more info.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) Update(set func(*CarpoolResetAnnouncementOutboxUpsert)) *CarpoolResetAnnouncementOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolResetAnnouncementOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetBatchID(v int64) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetBatchID(v)
	})
}

// AddBatchID adds v to the "batch_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) AddBatchID(v int64) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateBatchID() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateBatchID()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetScopeID(v int64) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetScopeID(v)
	})
}

// AddScopeID adds v to the "scope_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) AddScopeID(v int64) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateScopeID() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateScopeID()
	})
}

// SetEventKind sets the "event_kind" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetEventKind(v string) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetEventKind(v)
	})
}

// UpdateEventKind sets the "event_kind" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateEventKind() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateEventKind()
	})
}

// SetScheduleRevision sets the "schedule_revision" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetScheduleRevision(v int) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetScheduleRevision(v)
	})
}

// AddScheduleRevision adds v to the "schedule_revision" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) AddScheduleRevision(v int) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddScheduleRevision(v)
	})
}

// UpdateScheduleRevision sets the "schedule_revision" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateScheduleRevision() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateScheduleRevision()
	})
}

// SetStatus sets the "status" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetStatus(v string) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateStatus() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateStatus()
	})
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetAnnouncementID(v)
	})
}

// AddAnnouncementID adds v to the "announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) AddAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateAnnouncementID() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateAnnouncementID()
	})
}

// ClearAnnouncementID clears the value of the "announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) ClearAnnouncementID() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.ClearAnnouncementID()
	})
}

// SetOriginalAnnouncementID sets the "original_announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetOriginalAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetOriginalAnnouncementID(v)
	})
}

// AddOriginalAnnouncementID adds v to the "original_announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) AddOriginalAnnouncementID(v int64) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddOriginalAnnouncementID(v)
	})
}

// UpdateOriginalAnnouncementID sets the "original_announcement_id" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateOriginalAnnouncementID() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateOriginalAnnouncementID()
	})
}

// ClearOriginalAnnouncementID clears the value of the "original_announcement_id" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) ClearOriginalAnnouncementID() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.ClearOriginalAnnouncementID()
	})
}

// SetTitle sets the "title" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetTitle(v string) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateTitle() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetContent(v string) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateContent() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateContent()
	})
}

// SetAttempts sets the "attempts" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetAttempts(v int) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) AddAttempts(v int) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateAttempts() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateAttempts()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetNextAttemptAt(v time.Time) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateNextAttemptAt() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetLastError(v string) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateLastError() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) ClearLastError() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.ClearLastError()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetPublishedAt(v time.Time) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdatePublishedAt() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) ClearPublishedAt() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.ClearPublishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) SetUpdatedAt(v time.Time) *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) UpdateUpdatedAt() *CarpoolResetAnnouncementOutboxUpsertBulk {
	return u.Update(func(s *CarpoolResetAnnouncementOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarpoolResetAnnouncementOutboxCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolResetAnnouncementOutboxCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolResetAnnouncementOutboxUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
