// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolresettarget"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CarpoolResetTargetDelete is the builder for deleting a CarpoolResetTarget entity.
type CarpoolResetTargetDelete struct {
	config
	hooks    []Hook
	mutation *CarpoolResetTargetMutation
}

// Where appends a list predicates to the CarpoolResetTargetDelete builder.
func (_d *CarpoolResetTargetDelete) Where(ps ...predicate.CarpoolResetTarget) *CarpoolResetTargetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CarpoolResetTargetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolResetTargetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CarpoolResetTargetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(carpoolresettarget.Table, sqlgraph.NewFieldSpec(carpoolresettarget.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CarpoolResetTargetDeleteOne is the builder for deleting a single CarpoolResetTarget entity.
type CarpoolResetTargetDeleteOne struct {
	_d *CarpoolResetTargetDelete
}

// Where appends a list predicates to the CarpoolResetTargetDelete builder.
func (_d *CarpoolResetTargetDeleteOne) Where(ps ...predicate.CarpoolResetTarget) *CarpoolResetTargetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CarpoolResetTargetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{carpoolresettarget.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolResetTargetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
