// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolresetbatch"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CarpoolResetBatchDelete is the builder for deleting a CarpoolResetBatch entity.
type CarpoolResetBatchDelete struct {
	config
	hooks    []Hook
	mutation *CarpoolResetBatchMutation
}

// Where appends a list predicates to the CarpoolResetBatchDelete builder.
func (_d *CarpoolResetBatchDelete) Where(ps ...predicate.CarpoolResetBatch) *CarpoolResetBatchDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CarpoolResetBatchDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolResetBatchDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CarpoolResetBatchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(carpoolresetbatch.Table, sqlgraph.NewFieldSpec(carpoolresetbatch.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CarpoolResetBatchDeleteOne is the builder for deleting a single CarpoolResetBatch entity.
type CarpoolResetBatchDeleteOne struct {
	_d *CarpoolResetBatchDelete
}

// Where appends a list predicates to the CarpoolResetBatchDelete builder.
func (_d *CarpoolResetBatchDeleteOne) Where(ps ...predicate.CarpoolResetBatch) *CarpoolResetBatchDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CarpoolResetBatchDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{carpoolresetbatch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolResetBatchDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
