// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/carpoolbillingrequest"
)

// CarpoolBillingRequest is the model entity for the CarpoolBillingRequest schema.
type CarpoolBillingRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// TermID holds the value of the "term_id" field.
	TermID int64 `json:"term_id,omitempty"`
	// CycleID holds the value of the "cycle_id" field.
	CycleID int64 `json:"cycle_id,omitempty"`
	// AdmittedAt holds the value of the "admitted_at" field.
	AdmittedAt time.Time `json:"admitted_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint string `json:"request_fingerprint,omitempty"`
	// BillingPayload holds the value of the "billing_payload" field.
	BillingPayload map[string]interface{} `json:"billing_payload,omitempty"`
	// ActualCostUsd holds the value of the "actual_cost_usd" field.
	ActualCostUsd *float64 `json:"actual_cost_usd,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// ReceiptRecordedAt holds the value of the "receipt_recorded_at" field.
	ReceiptRecordedAt *time.Time `json:"receipt_recorded_at,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt *time.Time `json:"settled_at,omitempty"`
	// Resolution holds the value of the "resolution" field.
	Resolution *string `json:"resolution,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// ResolvedBy holds the value of the "resolved_by" field.
	ResolvedBy *int64 `json:"resolved_by,omitempty"`
	// ResolutionReason holds the value of the "resolution_reason" field.
	ResolutionReason *string `json:"resolution_reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CarpoolBillingRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carpoolbillingrequest.FieldBillingPayload:
			values[i] = new([]byte)
		case carpoolbillingrequest.FieldActualCostUsd:
			values[i] = new(sql.NullFloat64)
		case carpoolbillingrequest.FieldID, carpoolbillingrequest.FieldAPIKeyID, carpoolbillingrequest.FieldUserID, carpoolbillingrequest.FieldGroupID, carpoolbillingrequest.FieldTermID, carpoolbillingrequest.FieldCycleID, carpoolbillingrequest.FieldRetryCount, carpoolbillingrequest.FieldResolvedBy:
			values[i] = new(sql.NullInt64)
		case carpoolbillingrequest.FieldRequestID, carpoolbillingrequest.FieldStatus, carpoolbillingrequest.FieldRequestFingerprint, carpoolbillingrequest.FieldLastError, carpoolbillingrequest.FieldResolution, carpoolbillingrequest.FieldResolutionReason:
			values[i] = new(sql.NullString)
		case carpoolbillingrequest.FieldAdmittedAt, carpoolbillingrequest.FieldReceiptRecordedAt, carpoolbillingrequest.FieldSettledAt, carpoolbillingrequest.FieldResolvedAt, carpoolbillingrequest.FieldCreatedAt, carpoolbillingrequest.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CarpoolBillingRequest fields.
func (_m *CarpoolBillingRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carpoolbillingrequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case carpoolbillingrequest.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case carpoolbillingrequest.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case carpoolbillingrequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case carpoolbillingrequest.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case carpoolbillingrequest.FieldTermID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field term_id", values[i])
			} else if value.Valid {
				_m.TermID = value.Int64
			}
		case carpoolbillingrequest.FieldCycleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_id", values[i])
			} else if value.Valid {
				_m.CycleID = value.Int64
			}
		case carpoolbillingrequest.FieldAdmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field admitted_at", values[i])
			} else if value.Valid {
				_m.AdmittedAt = value.Time
			}
		case carpoolbillingrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case carpoolbillingrequest.FieldRequestFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value.Valid {
				_m.RequestFingerprint = value.String
			}
		case carpoolbillingrequest.FieldBillingPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field billing_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BillingPayload); err != nil {
					return fmt.Errorf("unmarshal field billing_payload: %w", err)
				}
			}
		case carpoolbillingrequest.FieldActualCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost_usd", values[i])
			} else if value.Valid {
				_m.ActualCostUsd = new(float64)
				*_m.ActualCostUsd = value.Float64
			}
		case carpoolbillingrequest.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case carpoolbillingrequest.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case carpoolbillingrequest.FieldReceiptRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field receipt_recorded_at", values[i])
			} else if value.Valid {
				_m.ReceiptRecordedAt = new(time.Time)
				*_m.ReceiptRecordedAt = value.Time
			}
		case carpoolbillingrequest.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		case carpoolbillingrequest.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				_m.Resolution = new(string)
				*_m.Resolution = value.String
			}
		case carpoolbillingrequest.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		case carpoolbillingrequest.FieldResolvedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_by", values[i])
			} else if value.Valid {
				_m.ResolvedBy = new(int64)
				*_m.ResolvedBy = value.Int64
			}
		case carpoolbillingrequest.FieldResolutionReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution_reason", values[i])
			} else if value.Valid {
				_m.ResolutionReason = new(string)
				*_m.ResolutionReason = value.String
			}
		case carpoolbillingrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case carpoolbillingrequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CarpoolBillingRequest.
// This includes values selected through modifiers, order, etc.
func (_m *CarpoolBillingRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CarpoolBillingRequest.
// Note that you need to call CarpoolBillingRequest.Unwrap() before calling this method if this CarpoolBillingRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CarpoolBillingRequest) Update() *CarpoolBillingRequestUpdateOne {
	return NewCarpoolBillingRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CarpoolBillingRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CarpoolBillingRequest) Unwrap() *CarpoolBillingRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CarpoolBillingRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CarpoolBillingRequest) String() string {
	var builder strings.Builder
	builder.WriteString("CarpoolBillingRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("term_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TermID))
	builder.WriteString(", ")
	builder.WriteString("cycle_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CycleID))
	builder.WriteString(", ")
	builder.WriteString("admitted_at=")
	builder.WriteString(_m.AdmittedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("request_fingerprint=")
	builder.WriteString(_m.RequestFingerprint)
	builder.WriteString(", ")
	builder.WriteString("billing_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingPayload))
	builder.WriteString(", ")
	if v := _m.ActualCostUsd; v != nil {
		builder.WriteString("actual_cost_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReceiptRecordedAt; v != nil {
		builder.WriteString("receipt_recorded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Resolution; v != nil {
		builder.WriteString("resolution=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResolvedBy; v != nil {
		builder.WriteString("resolved_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResolutionReason; v != nil {
		builder.WriteString("resolution_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CarpoolBillingRequests is a parsable slice of CarpoolBillingRequest.
type CarpoolBillingRequests []*CarpoolBillingRequest
