// Code generated by ent, DO NOT EDIT.

package carpoolresetannouncementoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the carpoolresetannouncementoutbox type in the database.
	Label = "carpool_reset_announcement_outbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBatchID holds the string denoting the batch_id field in the database.
	FieldBatchID = "batch_id"
	// FieldScopeID holds the string denoting the scope_id field in the database.
	FieldScopeID = "scope_id"
	// FieldEventKind holds the string denoting the event_kind field in the database.
	FieldEventKind = "event_kind"
	// FieldScheduleRevision holds the string denoting the schedule_revision field in the database.
	FieldScheduleRevision = "schedule_revision"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAnnouncementID holds the string denoting the announcement_id field in the database.
	FieldAnnouncementID = "announcement_id"
	// FieldOriginalAnnouncementID holds the string denoting the original_announcement_id field in the database.
	FieldOriginalAnnouncementID = "original_announcement_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the carpoolresetannouncementoutbox in the database.
	Table = "carpool_reset_announcement_outbox"
)

// Columns holds all SQL columns for carpoolresetannouncementoutbox fields.
var Columns = []string{
	FieldID,
	FieldBatchID,
	FieldScopeID,
	FieldEventKind,
	FieldScheduleRevision,
	FieldStatus,
	FieldAnnouncementID,
	FieldOriginalAnnouncementID,
	FieldTitle,
	FieldContent,
	FieldAttempts,
	FieldNextAttemptAt,
	FieldLastError,
	FieldPublishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventKindValidator is a validator for the "event_kind" field. It is called by the builders before save.
	EventKindValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// DefaultNextAttemptAt holds the default value on creation for the "next_attempt_at" field.
	DefaultNextAttemptAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CarpoolResetAnnouncementOutbox queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBatchID orders the results by the batch_id field.
func ByBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchID, opts...).ToFunc()
}

// ByScopeID orders the results by the scope_id field.
func ByScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeID, opts...).ToFunc()
}

// ByEventKind orders the results by the event_kind field.
func ByEventKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventKind, opts...).ToFunc()
}

// ByScheduleRevision orders the results by the schedule_revision field.
func ByScheduleRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduleRevision, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAnnouncementID orders the results by the announcement_id field.
func ByAnnouncementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnnouncementID, opts...).ToFunc()
}

// ByOriginalAnnouncementID orders the results by the original_announcement_id field.
func ByOriginalAnnouncementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalAnnouncementID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
