// Code generated by ent, DO NOT EDIT.

package carpoolpayment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldID, id))
}

// TermID applies equality check predicate on the "term_id" field. It's identical to TermIDEQ.
func TermID(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldTermID, v))
}

// AmountCny applies equality check predicate on the "amount_cny" field. It's identical to AmountCnyEQ.
func AmountCny(v float64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldAmountCny, v))
}

// PaymentKind applies equality check predicate on the "payment_kind" field. It's identical to PaymentKindEQ.
func PaymentKind(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldPaymentKind, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldPaidAt, v))
}

// Channel applies equality check predicate on the "channel" field. It's identical to ChannelEQ.
func Channel(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldChannel, v))
}

// ExternalOrderNo applies equality check predicate on the "external_order_no" field. It's identical to ExternalOrderNoEQ.
func ExternalOrderNo(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldExternalOrderNo, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldRequestID, v))
}

// RequestFingerprint applies equality check predicate on the "request_fingerprint" field. It's identical to RequestFingerprintEQ.
func RequestFingerprint(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldRequestFingerprint, v))
}

// RecordedBy applies equality check predicate on the "recorded_by" field. It's identical to RecordedByEQ.
func RecordedBy(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldRecordedBy, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldNotes, v))
}

// RecordedAt applies equality check predicate on the "recorded_at" field. It's identical to RecordedAtEQ.
func RecordedAt(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldRecordedAt, v))
}

// TermIDEQ applies the EQ predicate on the "term_id" field.
func TermIDEQ(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldTermID, v))
}

// TermIDNEQ applies the NEQ predicate on the "term_id" field.
func TermIDNEQ(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldTermID, v))
}

// TermIDIn applies the In predicate on the "term_id" field.
func TermIDIn(vs ...int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldTermID, vs...))
}

// TermIDNotIn applies the NotIn predicate on the "term_id" field.
func TermIDNotIn(vs ...int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldTermID, vs...))
}

// TermIDGT applies the GT predicate on the "term_id" field.
func TermIDGT(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldTermID, v))
}

// TermIDGTE applies the GTE predicate on the "term_id" field.
func TermIDGTE(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldTermID, v))
}

// TermIDLT applies the LT predicate on the "term_id" field.
func TermIDLT(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldTermID, v))
}

// TermIDLTE applies the LTE predicate on the "term_id" field.
func TermIDLTE(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldTermID, v))
}

// AmountCnyEQ applies the EQ predicate on the "amount_cny" field.
func AmountCnyEQ(v float64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldAmountCny, v))
}

// AmountCnyNEQ applies the NEQ predicate on the "amount_cny" field.
func AmountCnyNEQ(v float64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldAmountCny, v))
}

// AmountCnyIn applies the In predicate on the "amount_cny" field.
func AmountCnyIn(vs ...float64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldAmountCny, vs...))
}

// AmountCnyNotIn applies the NotIn predicate on the "amount_cny" field.
func AmountCnyNotIn(vs ...float64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldAmountCny, vs...))
}

// AmountCnyGT applies the GT predicate on the "amount_cny" field.
func AmountCnyGT(v float64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldAmountCny, v))
}

// AmountCnyGTE applies the GTE predicate on the "amount_cny" field.
func AmountCnyGTE(v float64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldAmountCny, v))
}

// AmountCnyLT applies the LT predicate on the "amount_cny" field.
func AmountCnyLT(v float64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldAmountCny, v))
}

// AmountCnyLTE applies the LTE predicate on the "amount_cny" field.
func AmountCnyLTE(v float64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldAmountCny, v))
}

// PaymentKindEQ applies the EQ predicate on the "payment_kind" field.
func PaymentKindEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldPaymentKind, v))
}

// PaymentKindNEQ applies the NEQ predicate on the "payment_kind" field.
func PaymentKindNEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldPaymentKind, v))
}

// PaymentKindIn applies the In predicate on the "payment_kind" field.
func PaymentKindIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldPaymentKind, vs...))
}

// PaymentKindNotIn applies the NotIn predicate on the "payment_kind" field.
func PaymentKindNotIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldPaymentKind, vs...))
}

// PaymentKindGT applies the GT predicate on the "payment_kind" field.
func PaymentKindGT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldPaymentKind, v))
}

// PaymentKindGTE applies the GTE predicate on the "payment_kind" field.
func PaymentKindGTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldPaymentKind, v))
}

// PaymentKindLT applies the LT predicate on the "payment_kind" field.
func PaymentKindLT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldPaymentKind, v))
}

// PaymentKindLTE applies the LTE predicate on the "payment_kind" field.
func PaymentKindLTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldPaymentKind, v))
}

// PaymentKindContains applies the Contains predicate on the "payment_kind" field.
func PaymentKindContains(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContains(FieldPaymentKind, v))
}

// PaymentKindHasPrefix applies the HasPrefix predicate on the "payment_kind" field.
func PaymentKindHasPrefix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasPrefix(FieldPaymentKind, v))
}

// PaymentKindHasSuffix applies the HasSuffix predicate on the "payment_kind" field.
func PaymentKindHasSuffix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasSuffix(FieldPaymentKind, v))
}

// PaymentKindEqualFold applies the EqualFold predicate on the "payment_kind" field.
func PaymentKindEqualFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEqualFold(FieldPaymentKind, v))
}

// PaymentKindContainsFold applies the ContainsFold predicate on the "payment_kind" field.
func PaymentKindContainsFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContainsFold(FieldPaymentKind, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldPaidAt, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldChannel, vs...))
}

// ChannelGT applies the GT predicate on the "channel" field.
func ChannelGT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldChannel, v))
}

// ChannelGTE applies the GTE predicate on the "channel" field.
func ChannelGTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldChannel, v))
}

// ChannelLT applies the LT predicate on the "channel" field.
func ChannelLT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldChannel, v))
}

// ChannelLTE applies the LTE predicate on the "channel" field.
func ChannelLTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldChannel, v))
}

// ChannelContains applies the Contains predicate on the "channel" field.
func ChannelContains(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContains(FieldChannel, v))
}

// ChannelHasPrefix applies the HasPrefix predicate on the "channel" field.
func ChannelHasPrefix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasPrefix(FieldChannel, v))
}

// ChannelHasSuffix applies the HasSuffix predicate on the "channel" field.
func ChannelHasSuffix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasSuffix(FieldChannel, v))
}

// ChannelEqualFold applies the EqualFold predicate on the "channel" field.
func ChannelEqualFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEqualFold(FieldChannel, v))
}

// ChannelContainsFold applies the ContainsFold predicate on the "channel" field.
func ChannelContainsFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContainsFold(FieldChannel, v))
}

// ExternalOrderNoEQ applies the EQ predicate on the "external_order_no" field.
func ExternalOrderNoEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldExternalOrderNo, v))
}

// ExternalOrderNoNEQ applies the NEQ predicate on the "external_order_no" field.
func ExternalOrderNoNEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldExternalOrderNo, v))
}

// ExternalOrderNoIn applies the In predicate on the "external_order_no" field.
func ExternalOrderNoIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldExternalOrderNo, vs...))
}

// ExternalOrderNoNotIn applies the NotIn predicate on the "external_order_no" field.
func ExternalOrderNoNotIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldExternalOrderNo, vs...))
}

// ExternalOrderNoGT applies the GT predicate on the "external_order_no" field.
func ExternalOrderNoGT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldExternalOrderNo, v))
}

// ExternalOrderNoGTE applies the GTE predicate on the "external_order_no" field.
func ExternalOrderNoGTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldExternalOrderNo, v))
}

// ExternalOrderNoLT applies the LT predicate on the "external_order_no" field.
func ExternalOrderNoLT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldExternalOrderNo, v))
}

// ExternalOrderNoLTE applies the LTE predicate on the "external_order_no" field.
func ExternalOrderNoLTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldExternalOrderNo, v))
}

// ExternalOrderNoContains applies the Contains predicate on the "external_order_no" field.
func ExternalOrderNoContains(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContains(FieldExternalOrderNo, v))
}

// ExternalOrderNoHasPrefix applies the HasPrefix predicate on the "external_order_no" field.
func ExternalOrderNoHasPrefix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasPrefix(FieldExternalOrderNo, v))
}

// ExternalOrderNoHasSuffix applies the HasSuffix predicate on the "external_order_no" field.
func ExternalOrderNoHasSuffix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasSuffix(FieldExternalOrderNo, v))
}

// ExternalOrderNoIsNil applies the IsNil predicate on the "external_order_no" field.
func ExternalOrderNoIsNil() predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIsNull(FieldExternalOrderNo))
}

// ExternalOrderNoNotNil applies the NotNil predicate on the "external_order_no" field.
func ExternalOrderNoNotNil() predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotNull(FieldExternalOrderNo))
}

// ExternalOrderNoEqualFold applies the EqualFold predicate on the "external_order_no" field.
func ExternalOrderNoEqualFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEqualFold(FieldExternalOrderNo, v))
}

// ExternalOrderNoContainsFold applies the ContainsFold predicate on the "external_order_no" field.
func ExternalOrderNoContainsFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContainsFold(FieldExternalOrderNo, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContainsFold(FieldRequestID, v))
}

// RequestFingerprintEQ applies the EQ predicate on the "request_fingerprint" field.
func RequestFingerprintEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintNEQ applies the NEQ predicate on the "request_fingerprint" field.
func RequestFingerprintNEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintIn applies the In predicate on the "request_fingerprint" field.
func RequestFingerprintIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintNotIn applies the NotIn predicate on the "request_fingerprint" field.
func RequestFingerprintNotIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintGT applies the GT predicate on the "request_fingerprint" field.
func RequestFingerprintGT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldRequestFingerprint, v))
}

// RequestFingerprintGTE applies the GTE predicate on the "request_fingerprint" field.
func RequestFingerprintGTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldRequestFingerprint, v))
}

// RequestFingerprintLT applies the LT predicate on the "request_fingerprint" field.
func RequestFingerprintLT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldRequestFingerprint, v))
}

// RequestFingerprintLTE applies the LTE predicate on the "request_fingerprint" field.
func RequestFingerprintLTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldRequestFingerprint, v))
}

// RequestFingerprintContains applies the Contains predicate on the "request_fingerprint" field.
func RequestFingerprintContains(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContains(FieldRequestFingerprint, v))
}

// RequestFingerprintHasPrefix applies the HasPrefix predicate on the "request_fingerprint" field.
func RequestFingerprintHasPrefix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasPrefix(FieldRequestFingerprint, v))
}

// RequestFingerprintHasSuffix applies the HasSuffix predicate on the "request_fingerprint" field.
func RequestFingerprintHasSuffix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasSuffix(FieldRequestFingerprint, v))
}

// RequestFingerprintEqualFold applies the EqualFold predicate on the "request_fingerprint" field.
func RequestFingerprintEqualFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEqualFold(FieldRequestFingerprint, v))
}

// RequestFingerprintContainsFold applies the ContainsFold predicate on the "request_fingerprint" field.
func RequestFingerprintContainsFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContainsFold(FieldRequestFingerprint, v))
}

// RecordedByEQ applies the EQ predicate on the "recorded_by" field.
func RecordedByEQ(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldRecordedBy, v))
}

// RecordedByNEQ applies the NEQ predicate on the "recorded_by" field.
func RecordedByNEQ(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldRecordedBy, v))
}

// RecordedByIn applies the In predicate on the "recorded_by" field.
func RecordedByIn(vs ...int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldRecordedBy, vs...))
}

// RecordedByNotIn applies the NotIn predicate on the "recorded_by" field.
func RecordedByNotIn(vs ...int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldRecordedBy, vs...))
}

// RecordedByGT applies the GT predicate on the "recorded_by" field.
func RecordedByGT(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldRecordedBy, v))
}

// RecordedByGTE applies the GTE predicate on the "recorded_by" field.
func RecordedByGTE(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldRecordedBy, v))
}

// RecordedByLT applies the LT predicate on the "recorded_by" field.
func RecordedByLT(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldRecordedBy, v))
}

// RecordedByLTE applies the LTE predicate on the "recorded_by" field.
func RecordedByLTE(v int64) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldRecordedBy, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldContainsFold(FieldNotes, v))
}

// RecordedAtEQ applies the EQ predicate on the "recorded_at" field.
func RecordedAtEQ(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldEQ(FieldRecordedAt, v))
}

// RecordedAtNEQ applies the NEQ predicate on the "recorded_at" field.
func RecordedAtNEQ(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNEQ(FieldRecordedAt, v))
}

// RecordedAtIn applies the In predicate on the "recorded_at" field.
func RecordedAtIn(vs ...time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldIn(FieldRecordedAt, vs...))
}

// RecordedAtNotIn applies the NotIn predicate on the "recorded_at" field.
func RecordedAtNotIn(vs ...time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldNotIn(FieldRecordedAt, vs...))
}

// RecordedAtGT applies the GT predicate on the "recorded_at" field.
func RecordedAtGT(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGT(FieldRecordedAt, v))
}

// RecordedAtGTE applies the GTE predicate on the "recorded_at" field.
func RecordedAtGTE(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldGTE(FieldRecordedAt, v))
}

// RecordedAtLT applies the LT predicate on the "recorded_at" field.
func RecordedAtLT(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLT(FieldRecordedAt, v))
}

// RecordedAtLTE applies the LTE predicate on the "recorded_at" field.
func RecordedAtLTE(v time.Time) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.FieldLTE(FieldRecordedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CarpoolPayment) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CarpoolPayment) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarpoolPayment) predicate.CarpoolPayment {
	return predicate.CarpoolPayment(sql.NotPredicates(p))
}
