// Code generated by ent, DO NOT EDIT.

package carpoolterm

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldUserID, v))
}

// ScopeID applies equality check predicate on the "scope_id" field. It's identical to ScopeIDEQ.
func ScopeID(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldScopeID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldGroupID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldPlanID, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldExpiresAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldStatus, v))
}

// BoostUsed applies equality check predicate on the "boost_used" field. It's identical to BoostUsedEQ.
func BoostUsed(v int) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldBoostUsed, v))
}

// SourceMode applies equality check predicate on the "source_mode" field. It's identical to SourceModeEQ.
func SourceMode(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldSourceMode, v))
}

// HistoryComplete applies equality check predicate on the "history_complete" field. It's identical to HistoryCompleteEQ.
func HistoryComplete(v bool) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldHistoryComplete, v))
}

// StatisticsSince applies equality check predicate on the "statistics_since" field. It's identical to StatisticsSinceEQ.
func StatisticsSince(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldStatisticsSince, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldCreatedBy, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldNotes, v))
}

// TerminatedAt applies equality check predicate on the "terminated_at" field. It's identical to TerminatedAtEQ.
func TerminatedAt(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldTerminatedAt, v))
}

// TerminatedBy applies equality check predicate on the "terminated_by" field. It's identical to TerminatedByEQ.
func TerminatedBy(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldTerminatedBy, v))
}

// TerminationReason applies equality check predicate on the "termination_reason" field. It's identical to TerminationReasonEQ.
func TerminationReason(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldTerminationReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldUserID, v))
}

// ScopeIDEQ applies the EQ predicate on the "scope_id" field.
func ScopeIDEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldScopeID, v))
}

// ScopeIDNEQ applies the NEQ predicate on the "scope_id" field.
func ScopeIDNEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldScopeID, v))
}

// ScopeIDIn applies the In predicate on the "scope_id" field.
func ScopeIDIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldScopeID, vs...))
}

// ScopeIDNotIn applies the NotIn predicate on the "scope_id" field.
func ScopeIDNotIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldScopeID, vs...))
}

// ScopeIDGT applies the GT predicate on the "scope_id" field.
func ScopeIDGT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldScopeID, v))
}

// ScopeIDGTE applies the GTE predicate on the "scope_id" field.
func ScopeIDGTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldScopeID, v))
}

// ScopeIDLT applies the LT predicate on the "scope_id" field.
func ScopeIDLT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldScopeID, v))
}

// ScopeIDLTE applies the LTE predicate on the "scope_id" field.
func ScopeIDLTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldScopeID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldGroupID, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldPlanID, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldExpiresAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldContainsFold(FieldStatus, v))
}

// BoostUsedEQ applies the EQ predicate on the "boost_used" field.
func BoostUsedEQ(v int) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldBoostUsed, v))
}

// BoostUsedNEQ applies the NEQ predicate on the "boost_used" field.
func BoostUsedNEQ(v int) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldBoostUsed, v))
}

// BoostUsedIn applies the In predicate on the "boost_used" field.
func BoostUsedIn(vs ...int) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldBoostUsed, vs...))
}

// BoostUsedNotIn applies the NotIn predicate on the "boost_used" field.
func BoostUsedNotIn(vs ...int) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldBoostUsed, vs...))
}

// BoostUsedGT applies the GT predicate on the "boost_used" field.
func BoostUsedGT(v int) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldBoostUsed, v))
}

// BoostUsedGTE applies the GTE predicate on the "boost_used" field.
func BoostUsedGTE(v int) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldBoostUsed, v))
}

// BoostUsedLT applies the LT predicate on the "boost_used" field.
func BoostUsedLT(v int) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldBoostUsed, v))
}

// BoostUsedLTE applies the LTE predicate on the "boost_used" field.
func BoostUsedLTE(v int) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldBoostUsed, v))
}

// SourceModeEQ applies the EQ predicate on the "source_mode" field.
func SourceModeEQ(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldSourceMode, v))
}

// SourceModeNEQ applies the NEQ predicate on the "source_mode" field.
func SourceModeNEQ(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldSourceMode, v))
}

// SourceModeIn applies the In predicate on the "source_mode" field.
func SourceModeIn(vs ...string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldSourceMode, vs...))
}

// SourceModeNotIn applies the NotIn predicate on the "source_mode" field.
func SourceModeNotIn(vs ...string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldSourceMode, vs...))
}

// SourceModeGT applies the GT predicate on the "source_mode" field.
func SourceModeGT(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldSourceMode, v))
}

// SourceModeGTE applies the GTE predicate on the "source_mode" field.
func SourceModeGTE(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldSourceMode, v))
}

// SourceModeLT applies the LT predicate on the "source_mode" field.
func SourceModeLT(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldSourceMode, v))
}

// SourceModeLTE applies the LTE predicate on the "source_mode" field.
func SourceModeLTE(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldSourceMode, v))
}

// SourceModeContains applies the Contains predicate on the "source_mode" field.
func SourceModeContains(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldContains(FieldSourceMode, v))
}

// SourceModeHasPrefix applies the HasPrefix predicate on the "source_mode" field.
func SourceModeHasPrefix(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldHasPrefix(FieldSourceMode, v))
}

// SourceModeHasSuffix applies the HasSuffix predicate on the "source_mode" field.
func SourceModeHasSuffix(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldHasSuffix(FieldSourceMode, v))
}

// SourceModeEqualFold applies the EqualFold predicate on the "source_mode" field.
func SourceModeEqualFold(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEqualFold(FieldSourceMode, v))
}

// SourceModeContainsFold applies the ContainsFold predicate on the "source_mode" field.
func SourceModeContainsFold(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldContainsFold(FieldSourceMode, v))
}

// HistoryCompleteEQ applies the EQ predicate on the "history_complete" field.
func HistoryCompleteEQ(v bool) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldHistoryComplete, v))
}

// HistoryCompleteNEQ applies the NEQ predicate on the "history_complete" field.
func HistoryCompleteNEQ(v bool) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldHistoryComplete, v))
}

// StatisticsSinceEQ applies the EQ predicate on the "statistics_since" field.
func StatisticsSinceEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldStatisticsSince, v))
}

// StatisticsSinceNEQ applies the NEQ predicate on the "statistics_since" field.
func StatisticsSinceNEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldStatisticsSince, v))
}

// StatisticsSinceIn applies the In predicate on the "statistics_since" field.
func StatisticsSinceIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldStatisticsSince, vs...))
}

// StatisticsSinceNotIn applies the NotIn predicate on the "statistics_since" field.
func StatisticsSinceNotIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldStatisticsSince, vs...))
}

// StatisticsSinceGT applies the GT predicate on the "statistics_since" field.
func StatisticsSinceGT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldStatisticsSince, v))
}

// StatisticsSinceGTE applies the GTE predicate on the "statistics_since" field.
func StatisticsSinceGTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldStatisticsSince, v))
}

// StatisticsSinceLT applies the LT predicate on the "statistics_since" field.
func StatisticsSinceLT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldStatisticsSince, v))
}

// StatisticsSinceLTE applies the LTE predicate on the "statistics_since" field.
func StatisticsSinceLTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldStatisticsSince, v))
}

// StatisticsSinceIsNil applies the IsNil predicate on the "statistics_since" field.
func StatisticsSinceIsNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIsNull(FieldStatisticsSince))
}

// StatisticsSinceNotNil applies the NotNil predicate on the "statistics_since" field.
func StatisticsSinceNotNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotNull(FieldStatisticsSince))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldCreatedBy, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldContainsFold(FieldNotes, v))
}

// TerminatedAtEQ applies the EQ predicate on the "terminated_at" field.
func TerminatedAtEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldTerminatedAt, v))
}

// TerminatedAtNEQ applies the NEQ predicate on the "terminated_at" field.
func TerminatedAtNEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldTerminatedAt, v))
}

// TerminatedAtIn applies the In predicate on the "terminated_at" field.
func TerminatedAtIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldTerminatedAt, vs...))
}

// TerminatedAtNotIn applies the NotIn predicate on the "terminated_at" field.
func TerminatedAtNotIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldTerminatedAt, vs...))
}

// TerminatedAtGT applies the GT predicate on the "terminated_at" field.
func TerminatedAtGT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldTerminatedAt, v))
}

// TerminatedAtGTE applies the GTE predicate on the "terminated_at" field.
func TerminatedAtGTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldTerminatedAt, v))
}

// TerminatedAtLT applies the LT predicate on the "terminated_at" field.
func TerminatedAtLT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldTerminatedAt, v))
}

// TerminatedAtLTE applies the LTE predicate on the "terminated_at" field.
func TerminatedAtLTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldTerminatedAt, v))
}

// TerminatedAtIsNil applies the IsNil predicate on the "terminated_at" field.
func TerminatedAtIsNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIsNull(FieldTerminatedAt))
}

// TerminatedAtNotNil applies the NotNil predicate on the "terminated_at" field.
func TerminatedAtNotNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotNull(FieldTerminatedAt))
}

// TerminatedByEQ applies the EQ predicate on the "terminated_by" field.
func TerminatedByEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldTerminatedBy, v))
}

// TerminatedByNEQ applies the NEQ predicate on the "terminated_by" field.
func TerminatedByNEQ(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldTerminatedBy, v))
}

// TerminatedByIn applies the In predicate on the "terminated_by" field.
func TerminatedByIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldTerminatedBy, vs...))
}

// TerminatedByNotIn applies the NotIn predicate on the "terminated_by" field.
func TerminatedByNotIn(vs ...int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldTerminatedBy, vs...))
}

// TerminatedByGT applies the GT predicate on the "terminated_by" field.
func TerminatedByGT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldTerminatedBy, v))
}

// TerminatedByGTE applies the GTE predicate on the "terminated_by" field.
func TerminatedByGTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldTerminatedBy, v))
}

// TerminatedByLT applies the LT predicate on the "terminated_by" field.
func TerminatedByLT(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldTerminatedBy, v))
}

// TerminatedByLTE applies the LTE predicate on the "terminated_by" field.
func TerminatedByLTE(v int64) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldTerminatedBy, v))
}

// TerminatedByIsNil applies the IsNil predicate on the "terminated_by" field.
func TerminatedByIsNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIsNull(FieldTerminatedBy))
}

// TerminatedByNotNil applies the NotNil predicate on the "terminated_by" field.
func TerminatedByNotNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotNull(FieldTerminatedBy))
}

// TerminationReasonEQ applies the EQ predicate on the "termination_reason" field.
func TerminationReasonEQ(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldTerminationReason, v))
}

// TerminationReasonNEQ applies the NEQ predicate on the "termination_reason" field.
func TerminationReasonNEQ(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldTerminationReason, v))
}

// TerminationReasonIn applies the In predicate on the "termination_reason" field.
func TerminationReasonIn(vs ...string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldTerminationReason, vs...))
}

// TerminationReasonNotIn applies the NotIn predicate on the "termination_reason" field.
func TerminationReasonNotIn(vs ...string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldTerminationReason, vs...))
}

// TerminationReasonGT applies the GT predicate on the "termination_reason" field.
func TerminationReasonGT(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldTerminationReason, v))
}

// TerminationReasonGTE applies the GTE predicate on the "termination_reason" field.
func TerminationReasonGTE(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldTerminationReason, v))
}

// TerminationReasonLT applies the LT predicate on the "termination_reason" field.
func TerminationReasonLT(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldTerminationReason, v))
}

// TerminationReasonLTE applies the LTE predicate on the "termination_reason" field.
func TerminationReasonLTE(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldTerminationReason, v))
}

// TerminationReasonContains applies the Contains predicate on the "termination_reason" field.
func TerminationReasonContains(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldContains(FieldTerminationReason, v))
}

// TerminationReasonHasPrefix applies the HasPrefix predicate on the "termination_reason" field.
func TerminationReasonHasPrefix(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldHasPrefix(FieldTerminationReason, v))
}

// TerminationReasonHasSuffix applies the HasSuffix predicate on the "termination_reason" field.
func TerminationReasonHasSuffix(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldHasSuffix(FieldTerminationReason, v))
}

// TerminationReasonIsNil applies the IsNil predicate on the "termination_reason" field.
func TerminationReasonIsNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIsNull(FieldTerminationReason))
}

// TerminationReasonNotNil applies the NotNil predicate on the "termination_reason" field.
func TerminationReasonNotNil() predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotNull(FieldTerminationReason))
}

// TerminationReasonEqualFold applies the EqualFold predicate on the "termination_reason" field.
func TerminationReasonEqualFold(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEqualFold(FieldTerminationReason, v))
}

// TerminationReasonContainsFold applies the ContainsFold predicate on the "termination_reason" field.
func TerminationReasonContainsFold(v string) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldContainsFold(FieldTerminationReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CarpoolTerm) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CarpoolTerm) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarpoolTerm) predicate.CarpoolTerm {
	return predicate.CarpoolTerm(sql.NotPredicates(p))
}
