// Code generated by ent, DO NOT EDIT.

package carpooloperation

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the carpooloperation type in the database.
	Label = "carpool_operation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldActorID holds the string denoting the actor_id field in the database.
	FieldActorID = "actor_id"
	// FieldKeyHash holds the string denoting the key_hash field in the database.
	FieldKeyHash = "key_hash"
	// FieldRequestFingerprint holds the string denoting the request_fingerprint field in the database.
	FieldRequestFingerprint = "request_fingerprint"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldResponse holds the string denoting the response field in the database.
	FieldResponse = "response"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the carpooloperation in the database.
	Table = "carpool_operations"
)

// Columns holds all SQL columns for carpooloperation fields.
var Columns = []string{
	FieldID,
	FieldKind,
	FieldActorID,
	FieldKeyHash,
	FieldRequestFingerprint,
	FieldResourceType,
	FieldResourceID,
	FieldResponse,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	KeyHashValidator func(string) error
	// RequestFingerprintValidator is a validator for the "request_fingerprint" field. It is called by the builders before save.
	RequestFingerprintValidator func(string) error
	// ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	ResourceTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CarpoolOperation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByActorID orders the results by the actor_id field.
func ByActorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorID, opts...).ToFunc()
}

// ByKeyHash orders the results by the key_hash field.
func ByKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyHash, opts...).ToFunc()
}

// ByRequestFingerprint orders the results by the request_fingerprint field.
func ByRequestFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestFingerprint, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
