// Code generated by ent, DO NOT EDIT.

package carpoolresettarget

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLTE(FieldID, id))
}

// BatchID applies equality check predicate on the "batch_id" field. It's identical to BatchIDEQ.
func BatchID(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldBatchID, v))
}

// TermID applies equality check predicate on the "term_id" field. It's identical to TermIDEQ.
func TermID(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldTermID, v))
}

// CycleID applies equality check predicate on the "cycle_id" field. It's identical to CycleIDEQ.
func CycleID(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldCycleID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldStatus, v))
}

// GrantedUsd applies equality check predicate on the "granted_usd" field. It's identical to GrantedUsdEQ.
func GrantedUsd(v float64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldGrantedUsd, v))
}

// ExecutedAt applies equality check predicate on the "executed_at" field. It's identical to ExecutedAtEQ.
func ExecutedAt(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldExecutedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// BatchIDEQ applies the EQ predicate on the "batch_id" field.
func BatchIDEQ(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldBatchID, v))
}

// BatchIDNEQ applies the NEQ predicate on the "batch_id" field.
func BatchIDNEQ(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNEQ(FieldBatchID, v))
}

// BatchIDIn applies the In predicate on the "batch_id" field.
func BatchIDIn(vs ...int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldIn(FieldBatchID, vs...))
}

// BatchIDNotIn applies the NotIn predicate on the "batch_id" field.
func BatchIDNotIn(vs ...int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNotIn(FieldBatchID, vs...))
}

// BatchIDGT applies the GT predicate on the "batch_id" field.
func BatchIDGT(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGT(FieldBatchID, v))
}

// BatchIDGTE applies the GTE predicate on the "batch_id" field.
func BatchIDGTE(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGTE(FieldBatchID, v))
}

// BatchIDLT applies the LT predicate on the "batch_id" field.
func BatchIDLT(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLT(FieldBatchID, v))
}

// BatchIDLTE applies the LTE predicate on the "batch_id" field.
func BatchIDLTE(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLTE(FieldBatchID, v))
}

// TermIDEQ applies the EQ predicate on the "term_id" field.
func TermIDEQ(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldTermID, v))
}

// TermIDNEQ applies the NEQ predicate on the "term_id" field.
func TermIDNEQ(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNEQ(FieldTermID, v))
}

// TermIDIn applies the In predicate on the "term_id" field.
func TermIDIn(vs ...int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldIn(FieldTermID, vs...))
}

// TermIDNotIn applies the NotIn predicate on the "term_id" field.
func TermIDNotIn(vs ...int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNotIn(FieldTermID, vs...))
}

// TermIDGT applies the GT predicate on the "term_id" field.
func TermIDGT(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGT(FieldTermID, v))
}

// TermIDGTE applies the GTE predicate on the "term_id" field.
func TermIDGTE(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGTE(FieldTermID, v))
}

// TermIDLT applies the LT predicate on the "term_id" field.
func TermIDLT(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLT(FieldTermID, v))
}

// TermIDLTE applies the LTE predicate on the "term_id" field.
func TermIDLTE(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLTE(FieldTermID, v))
}

// CycleIDEQ applies the EQ predicate on the "cycle_id" field.
func CycleIDEQ(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldCycleID, v))
}

// CycleIDNEQ applies the NEQ predicate on the "cycle_id" field.
func CycleIDNEQ(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNEQ(FieldCycleID, v))
}

// CycleIDIn applies the In predicate on the "cycle_id" field.
func CycleIDIn(vs ...int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldIn(FieldCycleID, vs...))
}

// CycleIDNotIn applies the NotIn predicate on the "cycle_id" field.
func CycleIDNotIn(vs ...int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNotIn(FieldCycleID, vs...))
}

// CycleIDGT applies the GT predicate on the "cycle_id" field.
func CycleIDGT(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGT(FieldCycleID, v))
}

// CycleIDGTE applies the GTE predicate on the "cycle_id" field.
func CycleIDGTE(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGTE(FieldCycleID, v))
}

// CycleIDLT applies the LT predicate on the "cycle_id" field.
func CycleIDLT(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLT(FieldCycleID, v))
}

// CycleIDLTE applies the LTE predicate on the "cycle_id" field.
func CycleIDLTE(v int64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLTE(FieldCycleID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldContainsFold(FieldStatus, v))
}

// GrantedUsdEQ applies the EQ predicate on the "granted_usd" field.
func GrantedUsdEQ(v float64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldGrantedUsd, v))
}

// GrantedUsdNEQ applies the NEQ predicate on the "granted_usd" field.
func GrantedUsdNEQ(v float64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNEQ(FieldGrantedUsd, v))
}

// GrantedUsdIn applies the In predicate on the "granted_usd" field.
func GrantedUsdIn(vs ...float64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldIn(FieldGrantedUsd, vs...))
}

// GrantedUsdNotIn applies the NotIn predicate on the "granted_usd" field.
func GrantedUsdNotIn(vs ...float64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNotIn(FieldGrantedUsd, vs...))
}

// GrantedUsdGT applies the GT predicate on the "granted_usd" field.
func GrantedUsdGT(v float64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGT(FieldGrantedUsd, v))
}

// GrantedUsdGTE applies the GTE predicate on the "granted_usd" field.
func GrantedUsdGTE(v float64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGTE(FieldGrantedUsd, v))
}

// GrantedUsdLT applies the LT predicate on the "granted_usd" field.
func GrantedUsdLT(v float64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLT(FieldGrantedUsd, v))
}

// GrantedUsdLTE applies the LTE predicate on the "granted_usd" field.
func GrantedUsdLTE(v float64) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLTE(FieldGrantedUsd, v))
}

// ExecutedAtEQ applies the EQ predicate on the "executed_at" field.
func ExecutedAtEQ(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldExecutedAt, v))
}

// ExecutedAtNEQ applies the NEQ predicate on the "executed_at" field.
func ExecutedAtNEQ(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNEQ(FieldExecutedAt, v))
}

// ExecutedAtIn applies the In predicate on the "executed_at" field.
func ExecutedAtIn(vs ...time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldIn(FieldExecutedAt, vs...))
}

// ExecutedAtNotIn applies the NotIn predicate on the "executed_at" field.
func ExecutedAtNotIn(vs ...time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNotIn(FieldExecutedAt, vs...))
}

// ExecutedAtGT applies the GT predicate on the "executed_at" field.
func ExecutedAtGT(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGT(FieldExecutedAt, v))
}

// ExecutedAtGTE applies the GTE predicate on the "executed_at" field.
func ExecutedAtGTE(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGTE(FieldExecutedAt, v))
}

// ExecutedAtLT applies the LT predicate on the "executed_at" field.
func ExecutedAtLT(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLT(FieldExecutedAt, v))
}

// ExecutedAtLTE applies the LTE predicate on the "executed_at" field.
func ExecutedAtLTE(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLTE(FieldExecutedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CarpoolResetTarget) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CarpoolResetTarget) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarpoolResetTarget) predicate.CarpoolResetTarget {
	return predicate.CarpoolResetTarget(sql.NotPredicates(p))
}
