// Code generated by ent, DO NOT EDIT.

package carpoolresetcredit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldID, id))
}

// AccountStateID applies equality check predicate on the "account_state_id" field. It's identical to AccountStateIDEQ.
func AccountStateID(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldAccountStateID, v))
}

// UpstreamIdentityHash applies equality check predicate on the "upstream_identity_hash" field. It's identical to UpstreamIdentityHashEQ.
func UpstreamIdentityHash(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldUpstreamIdentityHash, v))
}

// CreditHash applies equality check predicate on the "credit_hash" field. It's identical to CreditHashEQ.
func CreditHash(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldCreditHash, v))
}

// FirstSeenAt applies equality check predicate on the "first_seen_at" field. It's identical to FirstSeenAtEQ.
func FirstSeenAt(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldFirstSeenAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldLastSeenAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldExpiresAt, v))
}

// InitialStock applies equality check predicate on the "initial_stock" field. It's identical to InitialStockEQ.
func InitialStock(v bool) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldInitialStock, v))
}

// AssignmentStatus applies equality check predicate on the "assignment_status" field. It's identical to AssignmentStatusEQ.
func AssignmentStatus(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldAssignmentStatus, v))
}

// ResetBatchID applies equality check predicate on the "reset_batch_id" field. It's identical to ResetBatchIDEQ.
func ResetBatchID(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldResetBatchID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountStateIDEQ applies the EQ predicate on the "account_state_id" field.
func AccountStateIDEQ(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldAccountStateID, v))
}

// AccountStateIDNEQ applies the NEQ predicate on the "account_state_id" field.
func AccountStateIDNEQ(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldAccountStateID, v))
}

// AccountStateIDIn applies the In predicate on the "account_state_id" field.
func AccountStateIDIn(vs ...int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldAccountStateID, vs...))
}

// AccountStateIDNotIn applies the NotIn predicate on the "account_state_id" field.
func AccountStateIDNotIn(vs ...int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldAccountStateID, vs...))
}

// AccountStateIDGT applies the GT predicate on the "account_state_id" field.
func AccountStateIDGT(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldAccountStateID, v))
}

// AccountStateIDGTE applies the GTE predicate on the "account_state_id" field.
func AccountStateIDGTE(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldAccountStateID, v))
}

// AccountStateIDLT applies the LT predicate on the "account_state_id" field.
func AccountStateIDLT(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldAccountStateID, v))
}

// AccountStateIDLTE applies the LTE predicate on the "account_state_id" field.
func AccountStateIDLTE(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldAccountStateID, v))
}

// UpstreamIdentityHashEQ applies the EQ predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashEQ(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashNEQ applies the NEQ predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashNEQ(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashIn applies the In predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashIn(vs ...string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldUpstreamIdentityHash, vs...))
}

// UpstreamIdentityHashNotIn applies the NotIn predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashNotIn(vs ...string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldUpstreamIdentityHash, vs...))
}

// UpstreamIdentityHashGT applies the GT predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashGT(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashGTE applies the GTE predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashGTE(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashLT applies the LT predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashLT(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashLTE applies the LTE predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashLTE(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashContains applies the Contains predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashContains(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldContains(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashHasPrefix applies the HasPrefix predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashHasPrefix(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldHasPrefix(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashHasSuffix applies the HasSuffix predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashHasSuffix(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldHasSuffix(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashEqualFold applies the EqualFold predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashEqualFold(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEqualFold(FieldUpstreamIdentityHash, v))
}

// UpstreamIdentityHashContainsFold applies the ContainsFold predicate on the "upstream_identity_hash" field.
func UpstreamIdentityHashContainsFold(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldContainsFold(FieldUpstreamIdentityHash, v))
}

// CreditHashEQ applies the EQ predicate on the "credit_hash" field.
func CreditHashEQ(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldCreditHash, v))
}

// CreditHashNEQ applies the NEQ predicate on the "credit_hash" field.
func CreditHashNEQ(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldCreditHash, v))
}

// CreditHashIn applies the In predicate on the "credit_hash" field.
func CreditHashIn(vs ...string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldCreditHash, vs...))
}

// CreditHashNotIn applies the NotIn predicate on the "credit_hash" field.
func CreditHashNotIn(vs ...string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldCreditHash, vs...))
}

// CreditHashGT applies the GT predicate on the "credit_hash" field.
func CreditHashGT(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldCreditHash, v))
}

// CreditHashGTE applies the GTE predicate on the "credit_hash" field.
func CreditHashGTE(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldCreditHash, v))
}

// CreditHashLT applies the LT predicate on the "credit_hash" field.
func CreditHashLT(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldCreditHash, v))
}

// CreditHashLTE applies the LTE predicate on the "credit_hash" field.
func CreditHashLTE(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldCreditHash, v))
}

// CreditHashContains applies the Contains predicate on the "credit_hash" field.
func CreditHashContains(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldContains(FieldCreditHash, v))
}

// CreditHashHasPrefix applies the HasPrefix predicate on the "credit_hash" field.
func CreditHashHasPrefix(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldHasPrefix(FieldCreditHash, v))
}

// CreditHashHasSuffix applies the HasSuffix predicate on the "credit_hash" field.
func CreditHashHasSuffix(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldHasSuffix(FieldCreditHash, v))
}

// CreditHashEqualFold applies the EqualFold predicate on the "credit_hash" field.
func CreditHashEqualFold(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEqualFold(FieldCreditHash, v))
}

// CreditHashContainsFold applies the ContainsFold predicate on the "credit_hash" field.
func CreditHashContainsFold(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldContainsFold(FieldCreditHash, v))
}

// FirstSeenAtEQ applies the EQ predicate on the "first_seen_at" field.
func FirstSeenAtEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtNEQ applies the NEQ predicate on the "first_seen_at" field.
func FirstSeenAtNEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtIn applies the In predicate on the "first_seen_at" field.
func FirstSeenAtIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtNotIn applies the NotIn predicate on the "first_seen_at" field.
func FirstSeenAtNotIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtGT applies the GT predicate on the "first_seen_at" field.
func FirstSeenAtGT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldFirstSeenAt, v))
}

// FirstSeenAtGTE applies the GTE predicate on the "first_seen_at" field.
func FirstSeenAtGTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldFirstSeenAt, v))
}

// FirstSeenAtLT applies the LT predicate on the "first_seen_at" field.
func FirstSeenAtLT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldFirstSeenAt, v))
}

// FirstSeenAtLTE applies the LTE predicate on the "first_seen_at" field.
func FirstSeenAtLTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldFirstSeenAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldLastSeenAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotNull(FieldExpiresAt))
}

// InitialStockEQ applies the EQ predicate on the "initial_stock" field.
func InitialStockEQ(v bool) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldInitialStock, v))
}

// InitialStockNEQ applies the NEQ predicate on the "initial_stock" field.
func InitialStockNEQ(v bool) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldInitialStock, v))
}

// AssignmentStatusEQ applies the EQ predicate on the "assignment_status" field.
func AssignmentStatusEQ(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldAssignmentStatus, v))
}

// AssignmentStatusNEQ applies the NEQ predicate on the "assignment_status" field.
func AssignmentStatusNEQ(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldAssignmentStatus, v))
}

// AssignmentStatusIn applies the In predicate on the "assignment_status" field.
func AssignmentStatusIn(vs ...string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldAssignmentStatus, vs...))
}

// AssignmentStatusNotIn applies the NotIn predicate on the "assignment_status" field.
func AssignmentStatusNotIn(vs ...string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldAssignmentStatus, vs...))
}

// AssignmentStatusGT applies the GT predicate on the "assignment_status" field.
func AssignmentStatusGT(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldAssignmentStatus, v))
}

// AssignmentStatusGTE applies the GTE predicate on the "assignment_status" field.
func AssignmentStatusGTE(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldAssignmentStatus, v))
}

// AssignmentStatusLT applies the LT predicate on the "assignment_status" field.
func AssignmentStatusLT(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldAssignmentStatus, v))
}

// AssignmentStatusLTE applies the LTE predicate on the "assignment_status" field.
func AssignmentStatusLTE(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldAssignmentStatus, v))
}

// AssignmentStatusContains applies the Contains predicate on the "assignment_status" field.
func AssignmentStatusContains(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldContains(FieldAssignmentStatus, v))
}

// AssignmentStatusHasPrefix applies the HasPrefix predicate on the "assignment_status" field.
func AssignmentStatusHasPrefix(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldHasPrefix(FieldAssignmentStatus, v))
}

// AssignmentStatusHasSuffix applies the HasSuffix predicate on the "assignment_status" field.
func AssignmentStatusHasSuffix(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldHasSuffix(FieldAssignmentStatus, v))
}

// AssignmentStatusEqualFold applies the EqualFold predicate on the "assignment_status" field.
func AssignmentStatusEqualFold(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEqualFold(FieldAssignmentStatus, v))
}

// AssignmentStatusContainsFold applies the ContainsFold predicate on the "assignment_status" field.
func AssignmentStatusContainsFold(v string) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldContainsFold(FieldAssignmentStatus, v))
}

// ResetBatchIDEQ applies the EQ predicate on the "reset_batch_id" field.
func ResetBatchIDEQ(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldResetBatchID, v))
}

// ResetBatchIDNEQ applies the NEQ predicate on the "reset_batch_id" field.
func ResetBatchIDNEQ(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldResetBatchID, v))
}

// ResetBatchIDIn applies the In predicate on the "reset_batch_id" field.
func ResetBatchIDIn(vs ...int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldResetBatchID, vs...))
}

// ResetBatchIDNotIn applies the NotIn predicate on the "reset_batch_id" field.
func ResetBatchIDNotIn(vs ...int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldResetBatchID, vs...))
}

// ResetBatchIDGT applies the GT predicate on the "reset_batch_id" field.
func ResetBatchIDGT(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldResetBatchID, v))
}

// ResetBatchIDGTE applies the GTE predicate on the "reset_batch_id" field.
func ResetBatchIDGTE(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldResetBatchID, v))
}

// ResetBatchIDLT applies the LT predicate on the "reset_batch_id" field.
func ResetBatchIDLT(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldResetBatchID, v))
}

// ResetBatchIDLTE applies the LTE predicate on the "reset_batch_id" field.
func ResetBatchIDLTE(v int64) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldResetBatchID, v))
}

// ResetBatchIDIsNil applies the IsNil predicate on the "reset_batch_id" field.
func ResetBatchIDIsNil() predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIsNull(FieldResetBatchID))
}

// ResetBatchIDNotNil applies the NotNil predicate on the "reset_batch_id" field.
func ResetBatchIDNotNil() predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotNull(FieldResetBatchID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CarpoolResetCredit) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CarpoolResetCredit) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarpoolResetCredit) predicate.CarpoolResetCredit {
	return predicate.CarpoolResetCredit(sql.NotPredicates(p))
}
